import {
  UserProfile,
  UserAvailability,
  Subject,
  ScheduleTask,
  SpacedRevision,
  AITutor,
  LearningResource,
  Quiz,
  AcademicEvent,
  Achievement,
  NotificationItem,
} from '@/types';

export const initialProfile: UserProfile = {
  id: 'user-demo-1',
  email: 'student@cognistudy.ai',
  fullName: 'Dev Agarwal',
  educationLevel: 'Undergraduate',
  courseDegree: 'B.Tech in Computer Science',
  currentSemester: 'Semester 4',
  targetGpaGrade: '9.2 CGPA / Grade A+',
  dailyMaxStudyHours: 5.5,
  preferredStudyTime: 'evening',
  pomodoroFocusMins: 50,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 10,
  streakDays: 6,
  totalXp: 1450,
  onboardingCompleted: true,
  createdAt: '2026-08-01T00:00:00.000Z',
};

export const initialAvailability: UserAvailability = {
  userId: 'user-demo-1',
  dayType: 'weekday',
  wakeTime: '07:00',
  sleepTime: '23:30',
  institutionHours: '09:00-16:00',
  travelHours: '08:15-09:00, 16:00-16:45',
  mealHours: '08:00-08:30, 13:00-14:00, 20:00-20:45',
  personalActivityHours: '17:00-18:00',
  availableStudySlots: [
    { start: '18:00', end: '20:00' },
    { start: '20:45', end: '23:00' },
  ],
};

export const initialSubjects: Subject[] = [
  {
    id: 'subj-java',
    userId: 'user-demo-1',
    name: 'Java Programming',
    code: 'CS-204',
    color: '#6366f1', // Indigo
    icon: 'Code',
    targetMarks: 95,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 10 * 86400000).toISOString().split('T')[0], // 10 days away
    units: [
      {
        id: 'unit-java-1',
        subjectId: 'subj-java',
        unitNumber: 1,
        title: 'Java Fundamentals',
        chapters: [
          {
            id: 'chap-java-1',
            unitId: 'unit-java-1',
            chapterNumber: 1,
            title: 'Language Basics',
            estimatedBaseHours: 2.5,
            topics: [
              {
                id: 'top-java-vars',
                chapterId: 'chap-java-1',
                title: 'Variables & Data Types',
                difficulty: 'Easy',
                importance: 'Medium',
                knowledgeLevel: 'High',
                estimatedMins: 30,
                actualMinsSpent: 30,
                masteryPercentage: 95,
                isCompleted: true,
                keyDefinitions: ['Primitive Types (int, double, char)', 'Type Casting & Promotion'],
              },
              {
                id: 'top-java-control',
                chapterId: 'chap-java-1',
                title: 'Control Flow & Loops',
                difficulty: 'Easy',
                importance: 'High',
                knowledgeLevel: 'High',
                estimatedMins: 45,
                actualMinsSpent: 40,
                masteryPercentage: 90,
                isCompleted: true,
                prerequisiteIds: ['top-java-vars'],
              },
            ],
          },
        ],
      },
      {
        id: 'unit-java-2',
        subjectId: 'subj-java',
        unitNumber: 2,
        title: 'Object-Oriented Programming',
        chapters: [
          {
            id: 'chap-java-2',
            unitId: 'unit-java-2',
            chapterNumber: 2,
            title: 'Core OOP Principles',
            estimatedBaseHours: 4.0,
            topics: [
              {
                id: 'top-java-classes',
                chapterId: 'chap-java-2',
                title: 'Classes, Objects & Constructors',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'High',
                estimatedMins: 50,
                actualMinsSpent: 50,
                masteryPercentage: 88,
                isCompleted: true,
                prerequisiteIds: ['top-java-vars'],
              },
              {
                id: 'top-java-inheritance',
                chapterId: 'chap-java-2',
                title: 'Inheritance & Method Overriding',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 0,
                masteryPercentage: 65,
                isCompleted: false,
                prerequisiteIds: ['top-java-classes'],
                keyFormulas: ['super() keyword calling parent constructor', 'extends keyword'],
              },
              {
                id: 'top-java-polymorphism',
                chapterId: 'chap-java-2',
                title: 'Polymorphism & Interfaces',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 75,
                actualMinsSpent: 0,
                masteryPercentage: 55,
                isCompleted: false,
                prerequisiteIds: ['top-java-inheritance'],
              },
            ],
          },
        ],
      },
      {
        id: 'unit-java-3',
        subjectId: 'subj-java',
        unitNumber: 3,
        title: 'Advanced Java Architecture',
        chapters: [
          {
            id: 'chap-java-3',
            unitId: 'unit-java-3',
            chapterNumber: 3,
            title: 'Collections & Concurrency',
            estimatedBaseHours: 6.0,
            topics: [
              {
                id: 'top-java-threads',
                chapterId: 'chap-java-3',
                title: 'Multithreading & Synchronization',
                difficulty: 'Hard',
                importance: 'High',
                knowledgeLevel: 'Low',
                estimatedMins: 110,
                actualMinsSpent: 0,
                masteryPercentage: 35,
                isCompleted: false,
                prerequisiteIds: ['top-java-classes'],
              },
              {
                id: 'top-java-exceptions',
                chapterId: 'chap-java-3',
                title: 'Exception Handling & Custom Exceptions',
                difficulty: 'Medium',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 0,
                masteryPercentage: 50,
                isCompleted: false,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-calc',
    userId: 'user-demo-1',
    name: 'Calculus & Differential Equations',
    code: 'MATH-201',
    color: '#0ea5e9', // Sky
    icon: 'Sigma',
    targetMarks: 90,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 16 * 86400000).toISOString().split('T')[0], // 16 days away
    units: [
      {
        id: 'unit-calc-1',
        subjectId: 'subj-calc',
        unitNumber: 1,
        title: 'Advanced Integration',
        chapters: [
          {
            id: 'chap-calc-1',
            unitId: 'unit-calc-1',
            chapterNumber: 1,
            title: 'Techniques of Integration',
            estimatedBaseHours: 4.0,
            topics: [
              {
                id: 'top-calc-parts',
                chapterId: 'chap-calc-1',
                title: 'Integration by Parts & Reduction Formulas',
                difficulty: 'Medium',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 65,
                actualMinsSpent: 65,
                masteryPercentage: 80,
                isCompleted: true,
                keyFormulas: ['∫ u dv = uv - ∫ v du (LIATE rule)'],
              },
              {
                id: 'top-calc-ode',
                chapterId: 'chap-calc-1',
                title: 'First-Order Linear Differential Equations',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 90,
                actualMinsSpent: 0,
                masteryPercentage: 40,
                isCompleted: false,
                keyFormulas: ['Integrating Factor: IF = e^(∫ P(x)dx)', 'y * IF = ∫ (Q(x) * IF) dx + C'],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-dsa',
    userId: 'user-demo-1',
    name: 'Data Structures & Algorithms',
    code: 'CS-202',
    color: '#10b981', // Emerald
    icon: 'Binary',
    targetMarks: 95,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 24 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-dsa-1',
        subjectId: 'subj-dsa',
        unitNumber: 1,
        title: 'Trees & Graphs',
        chapters: [
          {
            id: 'chap-dsa-1',
            unitId: 'unit-dsa-1',
            chapterNumber: 1,
            title: 'Binary Trees & Traversals',
            estimatedBaseHours: 3.5,
            topics: [
              {
                id: 'top-dsa-trees',
                chapterId: 'chap-dsa-1',
                title: 'Binary Search Tree Operations & Balancing',
                difficulty: 'Hard',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 75,
                actualMinsSpent: 0,
                masteryPercentage: 58,
                isCompleted: false,
              },
            ],
          },
        ],
      },
    ],
  },
];

const todayStr = new Date().toISOString().split('T')[0];

export const initialScheduleTasks: ScheduleTask[] = [
  {
    id: 'task-1',
    userId: 'user-demo-1',
    topicId: 'top-java-inheritance',
    subjectId: 'subj-java',
    title: 'Java — Inheritance & Method Overriding',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    taskType: 'study',
    startTime: `${todayStr}T18:00:00`,
    endTime: `${todayStr}T19:00:00`,
    plannedDurationMins: 60,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
  },
  {
    id: 'task-break-1',
    userId: 'user-demo-1',
    title: 'Quick Recharge Break ☕',
    taskType: 'break',
    startTime: `${todayStr}T19:00:00`,
    endTime: `${todayStr}T19:10:00`,
    plannedDurationMins: 10,
    status: 'pending',
    isLocked: true,
    priorityTag: 'Low',
  },
  {
    id: 'task-2',
    userId: 'user-demo-1',
    topicId: 'top-java-polymorphism',
    subjectId: 'subj-java',
    title: 'Java — Polymorphism & Interfaces',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    taskType: 'study',
    startTime: `${todayStr}T19:10:00`,
    endTime: `${todayStr}T20:00:00`,
    plannedDurationMins: 50,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
  },
  {
    id: 'task-break-dinner',
    userId: 'user-demo-1',
    title: 'Dinner & Relaxation 🍲',
    taskType: 'break',
    startTime: `${todayStr}T20:00:00`,
    endTime: `${todayStr}T20:45:00`,
    plannedDurationMins: 45,
    status: 'pending',
    isLocked: true,
    priorityTag: 'Low',
  },
  {
    id: 'task-3',
    userId: 'user-demo-1',
    topicId: 'top-calc-ode',
    subjectId: 'subj-calc',
    title: 'Calculus — First-Order Differential Equations',
    subjectName: 'Calculus & Differential Equations',
    subjectColor: '#0ea5e9',
    taskType: 'study',
    startTime: `${todayStr}T20:45:00`,
    endTime: `${todayStr}T22:00:00`,
    plannedDurationMins: 75,
    status: 'pending',
    isLocked: false,
    priorityTag: 'High',
  },
  {
    id: 'task-4',
    userId: 'user-demo-1',
    topicId: 'top-java-vars',
    subjectId: 'subj-java',
    title: 'Java Fundamentals — Spaced Recall Quiz',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    taskType: 'revision',
    startTime: `${todayStr}T22:00:00`,
    endTime: `${todayStr}T22:30:00`,
    plannedDurationMins: 30,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Medium',
  },
];

export const initialSpacedRevisions: SpacedRevision[] = [
  {
    id: 'rev-1',
    userId: 'user-demo-1',
    topicId: 'top-java-classes',
    topicTitle: 'Classes, Objects & Constructors',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    repetitionNumber: 2,
    easeFactor: 2.6,
    intervalDays: 3,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 4,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rev-2',
    userId: 'user-demo-1',
    topicId: 'top-calc-parts',
    topicTitle: 'Integration by Parts & Reduction Formulas',
    subjectName: 'Calculus & Differential Equations',
    subjectColor: '#0ea5e9',
    repetitionNumber: 1,
    easeFactor: 2.36,
    intervalDays: 1,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rev-3',
    userId: 'user-demo-1',
    topicId: 'top-java-threads',
    topicTitle: 'Multithreading & Synchronization',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    repetitionNumber: 1,
    easeFactor: 1.9,
    intervalDays: 1,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 2,
    updatedAt: new Date().toISOString(),
  },
];

export const initialAITutors: AITutor[] = [
  {
    id: 'tutor-java',
    userId: 'user-demo-1',
    name: 'Duke — Java Specialist',
    avatarEmoji: '☕',
    subjectId: 'subj-java',
    subjectName: 'Java Programming',
    personality: 'Socratic & Code-Centric',
    systemPrompt:
      'You are Duke, an expert Java Computer Science professor. Explain OOP, design patterns, and JVM concepts clearly using concise code snippets and intuitive analogies.',
    isDefault: true,
  },
  {
    id: 'tutor-calc',
    userId: 'user-demo-1',
    name: 'Euler — Calculus Mentor',
    avatarEmoji: '📐',
    subjectId: 'subj-calc',
    subjectName: 'Calculus & Differential Equations',
    personality: 'Step-by-Step & Intuitive',
    systemPrompt:
      'You are Euler, an encouraging mathematics tutor. Provide clear step-by-step derivations, verify formulas, and guide students through calculus problems without skipping algebraic steps.',
    isDefault: false,
  },
  {
    id: 'tutor-exam',
    userId: 'user-demo-1',
    name: 'Strategist — Exam Prep Bot',
    avatarEmoji: '🎯',
    personality: 'Tactical & High-Yield',
    systemPrompt:
      'You are an exam strategy coach. Focus on high-yield exam questions, marking schemes, common traps, time management during tests, and high-frequency topics.',
    isDefault: false,
  },
  {
    id: 'tutor-doubt',
    userId: 'user-demo-1',
    name: 'Clarifier — Rapid Doubt Solver',
    avatarEmoji: '💡',
    personality: 'Ultra-Concise & Direct',
    systemPrompt:
      'You are a direct doubt solver. Give crystal-clear answers in 3 sentences or less, followed by 1 quick example.',
    isDefault: false,
  },
];

export const initialLearningResources: LearningResource[] = [
  {
    id: 'res-1',
    topicId: 'top-java-threads',
    topicTitle: 'Multithreading & Synchronization',
    subjectName: 'Java Programming',
    title: 'Java Multithreading & Concurrency in 45 Minutes',
    resourceType: 'video',
    url: 'https://youtube.com',
    difficultyLevel: 'Medium',
    estimatedMins: 45,
    recommendedReason:
      'Visual thread lifecycle diagrams that demystify race conditions and mutex locks.',
    qualityScore: 4.9,
    sourcePlatform: 'YouTube / JavaBrains',
  },
  {
    id: 'res-2',
    topicId: 'top-java-threads',
    topicTitle: 'Multithreading & Synchronization',
    subjectName: 'Java Programming',
    title: 'Oracle Official Java Docs: Concurrency Lesson',
    resourceType: 'documentation',
    url: 'https://docs.oracle.com',
    difficultyLevel: 'Hard',
    estimatedMins: 30,
    recommendedReason:
      'Authoritative technical reference for synchronized methods and volatile keyword.',
    qualityScore: 4.8,
    sourcePlatform: 'Oracle Documentation',
  },
  {
    id: 'res-3',
    topicId: 'top-java-inheritance',
    topicTitle: 'Inheritance & Method Overriding',
    subjectName: 'Java Programming',
    title: 'Interactive OOP Practice: Animals, Vehicles & Polymorphism',
    resourceType: 'practice',
    url: 'https://exercism.org',
    difficultyLevel: 'Medium',
    estimatedMins: 25,
    recommendedReason:
      'Hands-on coding exercises testing method overriding and abstract methods.',
    qualityScore: 4.7,
    sourcePlatform: 'Exercism / Coding',
  },
  {
    id: 'res-4',
    topicId: 'top-calc-ode',
    topicTitle: 'First-Order Linear Differential Equations',
    subjectName: 'Calculus & Differential Equations',
    title: 'Solving Linear ODEs with Integrating Factors Step-by-Step',
    resourceType: 'article',
    url: 'https://khanacademy.org',
    difficultyLevel: 'Medium',
    estimatedMins: 20,
    recommendedReason:
      'Crisp visual walkthrough showing exactly when and how to compute IF = e^(∫P dx).',
    qualityScore: 4.9,
    sourcePlatform: 'Khan Academy',
  },
];

export const initialQuizzes: Quiz[] = [
  {
    id: 'quiz-java-oop',
    userId: 'user-demo-1',
    topicId: 'top-java-inheritance',
    subjectId: 'subj-java',
    title: 'Java OOP & Inheritance Mastery Check',
    difficulty: 'Medium',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q1',
        questionText:
          'In Java, which keyword is used by a subclass to invoke a constructor of its immediate superclass?',
        questionType: 'mcq',
        options: ['this()', 'super()', 'parent()', 'base()'],
        correctAnswer: 'super()',
        explanation:
          'The super() keyword invokes the superclass constructor and must be the first statement in the subclass constructor.',
        difficulty: 'Easy',
      },
      {
        id: 'q2',
        questionText:
          'Does Java support multiple inheritance of classes (e.g. class C extends A, B)?',
        questionType: 'true_false',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation:
          'Java avoids multiple inheritance of state to prevent the Diamond Problem, but supports multiple inheritance of type through interfaces.',
        difficulty: 'Medium',
      },
      {
        id: 'q3',
        questionText:
          'What happens if a subclass defines a method with the exact same name and signature as a method in its superclass, but with a stricter access modifier (e.g., public to private)?',
        questionType: 'mcq',
        options: [
          'It compiles normally with runtime warning',
          'Compilation error: Cannot reduce the visibility of the inherited method',
          'It creates an overloaded method',
          'The superclass method is silently replaced',
        ],
        correctAnswer:
          'Compilation error: Cannot reduce the visibility of the inherited method',
        explanation:
          'In Java, an overriding method cannot have a more restrictive access modifier than the superclass method.',
        difficulty: 'Hard',
      },
    ],
  },
];

export const initialAcademicEvents: AcademicEvent[] = [
  {
    id: 'event-1',
    userId: 'user-demo-1',
    subjectId: 'subj-java',
    subjectName: 'Java Programming',
    subjectColor: '#6366f1',
    title: 'Final End-Semester Exam',
    eventType: 'final_exam',
    eventDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    weightagePercentage: 50,
    syllabusCoverageNeeded: 100,
  },
  {
    id: 'event-2',
    userId: 'user-demo-1',
    subjectId: 'subj-calc',
    subjectName: 'Calculus & Differential Equations',
    subjectColor: '#0ea5e9',
    title: 'Midterm Evaluation',
    eventType: 'midterm',
    eventDate: new Date(Date.now() + 16 * 86400000).toISOString(),
    weightagePercentage: 30,
    syllabusCoverageNeeded: 75,
  },
  {
    id: 'event-3',
    userId: 'user-demo-1',
    subjectId: 'subj-dsa',
    subjectName: 'Data Structures & Algorithms',
    subjectColor: '#10b981',
    title: 'Tree Data Structures Practical Lab',
    eventType: 'practical',
    eventDate: new Date(Date.now() + 4 * 86400000).toISOString(),
    weightagePercentage: 20,
    syllabusCoverageNeeded: 50,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    badgeId: 'streak-7',
    title: 'Consistency Titan',
    description: 'Maintained a continuous 6-day active study streak!',
    icon: '🔥',
    unlockedAt: '2026-08-25T19:00:00.000Z',
  },
  {
    id: 'ach-2',
    badgeId: 'topics-10',
    title: 'Syllabus Conqueror',
    description: 'Mastered over 10 academic topics with >80% retention.',
    icon: '📚',
    unlockedAt: '2026-08-22T21:00:00.000Z',
  },
  {
    id: 'ach-3',
    badgeId: 'early-bird',
    title: 'Hyper Focus Hero',
    description: 'Completed 3 study tasks early with >85% focus score.',
    icon: '⚡',
    unlockedAt: '2026-08-26T18:30:00.000Z',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-demo-1',
    title: 'Dynamic Scheduler Ready ⚡',
    message:
      'Your evening study plan for Java and Calculus is active. Start session when ready!',
    notificationType: 'schedule_update',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-demo-1',
    title: 'Java Exam in 10 Days 🎯',
    message:
      'High priority units: OOP Principles & Concurrency are prioritized in this week’s timetable.',
    notificationType: 'exam_warning',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
];
