import {
  UserProfile,
  UserAvailability,
  Subject,
  ScheduleTask,
  SpacedRevision,
  AITutor,
  LearningResource,
  Quiz,
  AcademicEvent,
  Achievement,
  NotificationItem,
  CheatsheetItem,
  BattleQuestion,
  BattleChallenger,
  LeaderboardEntry,
  StudentBattleProfile,
  IGOTCourse,
  CompetencyDomain,
  CompetencySkill,
  UploadedLearningMaterial,
  DepartmentWorkforceMetric,
  EmergingSkillPrediction,
} from '@/types';

// ==============================================================================
// 1. Government Official Competency Profiles
// ==============================================================================

export const initialProfile: UserProfile = {
  id: 'user-official-1',
  email: 'rajesh.kumar@mospi.gov.in',
  fullName: 'Rajesh Kumar, ISS',
  role: 'learner',
  designation: 'Senior Statistical Officer (SSO)',
  department: 'National Accounts Division (NAD), MoSPI',
  cadre: 'Indian Statistical Service (Subordinate / State Cadre)',
  currentAssignment: 'Compilation of Annual Estimates of GDP & GVA by Economic Activity',
  jobRole: 'Macroeconomic Aggregate Compiler & Survey Data Analyst',
  educationalQualification: 'M.Sc. in Statistics (ISI Kolkata), PG Diploma in Data Analytics',
  workExperience: '7+ Years in National Sample Surveys (NSS) & National Accounts compilation',
  previousTraining: [
    'NSSTA Induction Training Programme (Batch 2018)',
    'UNSIAP E-Learning on 2008 System of National Accounts (SNA)',
    'iGOT Karmayogi: Code of Ethics in Public Service',
  ],
  completedCourses: [
    'iGOT: Statistical Data Quality Assurance',
    'NSSTA: Survey Sampling & Estimation Techniques',
  ],
  currentCompetencyLevels: {
    'National Accounts': 84,
    'Survey Design': 76,
    'Sampling': 82,
    'Price Statistics': 70,
    'Labour Statistics': 68,
    'Data Quality Frameworks': 75,
    'Python': 54,
    'R': 62,
    'SQL': 58,
    'Data Visualization': 48,
    'AI/ML': 42,
    'GIS & Spatial Analytics': 38,
    'Cybersecurity': 55,
    'Data Privacy': 64,
    'Digital Public Infrastructure': 70,
    'Leadership': 72,
    'Communication': 75,
    'Project Management': 68,
    'Ethics in Statistics': 88,
  },
  overallCompetencyScore: 72,
  dailyMaxStudyHours: 2.0,
  streakDays: 14,
  totalXp: 3420,
  learningHoursLogged: 46.5,
  onboardingCompleted: true,
  createdAt: '2026-01-15T00:00:00.000Z',

  // Backward compatibility fields
  courseDegree: 'Capacity Building: Indian Official Statistical System',
  currentSemester: 'Quarter 3 Focus: Technical & Data Visualization',
  targetGpaGrade: 'Target Competency: 85%+',
  preferredStudyTime: 'morning',
  pomodoroFocusMins: 45,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const demoTrainerProfile: UserProfile = {
  id: 'user-trainer-1',
  email: 'sunita.sharma@nssta.gov.in',
  fullName: 'Dr. Sunita Sharma',
  role: 'trainer',
  designation: 'Director & Head of Faculty',
  department: 'National Statistical Systems Training Academy (NSSTA), Greater Noida',
  cadre: 'Senior Administrative Grade (SAG), ISS',
  currentAssignment: 'Statistical Curriculum Development & TPAC Competency Assessment',
  jobRole: 'Chief Statistical Trainer & Assessment Architect',
  educationalQualification: 'Ph.D. in Econometrics & Statistical Inference (Delhi University)',
  workExperience: '22 Years in MoSPI, CSO, and International Statistical Training (UNSIAP)',
  previousTraining: ['Advanced Statistical Training Geneva', 'iGOT Master Trainer Certification'],
  completedCourses: ['iGOT Karmayogi Master Faculty Module'],
  currentCompetencyLevels: {
    'National Accounts': 96,
    'Survey Design': 94,
    'Data Quality Frameworks': 95,
    'Python': 82,
    'AI/ML': 78,
  },
  overallCompetencyScore: 92,
  dailyMaxStudyHours: 4.0,
  streakDays: 32,
  totalXp: 9800,
  learningHoursLogged: 120.0,
  onboardingCompleted: true,
  createdAt: '2025-10-01T00:00:00.000Z',
  pomodoroFocusMins: 50,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const demoAdminProfile: UserProfile = {
  id: 'user-admin-1',
  email: 'dg.cadre@mospi.gov.in',
  fullName: 'P. Venkatachalam, ISS',
  role: 'admin',
  designation: 'Additional Director General (ADG - Human Resource & Training)',
  department: 'Ministry of Statistics and Programme Implementation (MoSPI)',
  cadre: 'Higher Administrative Grade (HAG), Indian Statistical Service',
  currentAssignment: 'MoSPI Workforce Capacity Building & iGOT Integration Strategy',
  jobRole: 'National Cadre Administrator & Skill Intelligence Lead',
  educationalQualification: 'M.Stat, M.Phil in Population Studies',
  workExperience: '28 Years in Official Statistics Governance',
  previousTraining: ['Senior Civil Servants Leadership Programme (LBSNAA)'],
  completedCourses: ['iGOT Karmayogi Executive Leadership'],
  currentCompetencyLevels: {
    'National Accounts': 90,
    'Leadership': 95,
    'Digital Public Infrastructure': 88,
  },
  overallCompetencyScore: 90,
  dailyMaxStudyHours: 2.0,
  streakDays: 45,
  totalXp: 12400,
  learningHoursLogged: 150.0,
  onboardingCompleted: true,
  createdAt: '2025-06-01T00:00:00.000Z',
  pomodoroFocusMins: 45,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const initialAvailability: UserAvailability = {
  userId: 'user-official-1',
  dayType: 'weekday',
  wakeTime: '06:30',
  sleepTime: '23:00',
  institutionHours: '09:30-18:00', // Ministry office hours
  travelHours: '08:30-09:30, 18:00-19:00',
  mealHours: '08:00-08:30, 13:00-14:00, 20:30-21:15',
  personalActivityHours: '19:00-20:00',
  availableStudySlots: [
    { start: '07:00', end: '08:15' }, // Pre-office focus window
    { start: '21:15', end: '22:30' }, // Evening capacity building window
  ],
};

// ==============================================================================
// 2. The Four Statistical Competency Domains & Skills
// ==============================================================================

export const initialCompetencyDomains: CompetencyDomain[] = [
  {
    id: 'domain-statistical',
    name: 'Statistical Competencies',
    code: 'STAT-DOM',
    color: '#3b82f6', // Official Blue
    icon: 'BarChart2',
    averageScore: 78,
    requiredBenchmark: 80,
    skills: [
      {
        id: 'skill-survey-design',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'Survey Design & Questionnaire Formulation',
        currentLevel: 76,
        requiredLevel: 85,
        gapSeverity: 'improvement_needed',
        gapPercentage: 9,
        aiRationale: 'Questionnaire cognitive testing and computer-assisted interview (CAPI) flows need alignment with latest NSS standards.',
        priority: 'High',
        recommendedActions: ['Complete NSSTA CAPI Survey Instrument design module'],
        keyManualsAndStandards: ['NSS Survey Handbook 2024', 'UN Household Survey Guidelines'],
        relatedIgotCourseIds: ['igot-c-survey-design'],
      },
      {
        id: 'skill-sampling',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'Sampling Theory & Weight Calibration',
        currentLevel: 82,
        requiredLevel: 80,
        gapSeverity: 'strong',
        gapPercentage: -2,
        aiRationale: 'Demonstrated solid grasp of stratified multi-stage cluster sampling and post-stratification adjustment factors.',
        priority: 'Medium',
        recommendedActions: ['Serve as mentor for junior statistical investigators'],
        keyManualsAndStandards: ['Cochran Sampling Techniques', 'MoSPI Technical Paper on Weight Calibration'],
        relatedIgotCourseIds: ['igot-c-sampling'],
      },
      {
        id: 'skill-national-accounts',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'National Accounts (SNA 2008 & GVA Compilation)',
        currentLevel: 84,
        requiredLevel: 85,
        gapSeverity: 'strong',
        gapPercentage: 1,
        aiRationale: 'Strong capability in Supply and Use Tables (SUT) and institutional sector accounts; minor update needed for digital economy valuation.',
        priority: 'Medium',
        recommendedActions: ['Review UN handbook on Measuring the Digital Economy within National Accounts'],
        keyManualsAndStandards: ['UN System of National Accounts 2008', 'MoSPI National Accounts Statistics Sources & Methods'],
        relatedIgotCourseIds: ['igot-c-national-accounts'],
      },
      {
        id: 'skill-price-statistics',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'Price Statistics (CPI, WPI & IIP Deflators)',
        currentLevel: 70,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 10,
        aiRationale: 'Hedonic regression for quality changes and chain-linked Laspeyres index methodology require upskilling.',
        priority: 'High',
        recommendedActions: ['Enrol in NSSTA Price Indices & Scanner Data Workshop'],
        keyManualsAndStandards: ['ILO Consumer Price Index Manual', 'MoSPI CPI Base Revision Guidelines'],
        relatedIgotCourseIds: ['igot-c-cpi'],
      },
      {
        id: 'skill-labour-statistics',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'Labour Statistics & PLFS Indicator Calculation',
        currentLevel: 68,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 12,
        aiRationale: 'Current status vs Usual status measurement disparities and sampling variance in quarterly urban PLFS estimates require targeted training.',
        priority: 'High',
        recommendedActions: ['Complete iGOT Labour Market Indicator Standards course'],
        keyManualsAndStandards: ['PLFS Instructions to Field Staff Vol. I & II', 'ILO Resolution Concerning Statistics of Work'],
        relatedIgotCourseIds: ['igot-c-plfs'],
      },
      {
        id: 'skill-sdg',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'SDG National Indicator Framework (NIF) & Metadata',
        currentLevel: 72,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 3,
        aiRationale: 'Good knowledge of Tier I indicators; needs upskilling on data disaggregation by vulnerable groups for Tier II indicators.',
        priority: 'Medium',
        recommendedActions: ['Study UNSIAP SDG Data Disaggregation toolkit'],
        keyManualsAndStandards: ['MoSPI National Indicator Framework Baseline Report', 'UN SDG Metadata Guidelines'],
        relatedIgotCourseIds: ['igot-c-sdg'],
      },
      {
        id: 'skill-data-quality',
        domainId: 'domain-statistical',
        domainName: 'Statistical Competencies',
        title: 'Data Quality Frameworks (NQAF / DQAF)',
        currentLevel: 75,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 5,
        aiRationale: 'Understanding of accuracy and timeliness is strong; metadata documentation consistency across line ministries can be improved.',
        priority: 'Medium',
        recommendedActions: ['Adopt the MoSPI National Quality Assurance Framework checklist'],
        keyManualsAndStandards: ['UN National Quality Assurance Framework (UN-NQAF)', 'IMF DQAF Manual'],
        relatedIgotCourseIds: ['igot-c-data-quality'],
      },
    ],
  },
  {
    id: 'domain-technical',
    name: 'Technical Competencies',
    code: 'TECH-DOM',
    color: '#0ea5e9', // Sky / Tech Blue
    icon: 'Terminal',
    averageScore: 52,
    requiredBenchmark: 75,
    skills: [
      {
        id: 'skill-python',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'Python for Official Statistics & Automation',
        currentLevel: 54,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 21,
        aiRationale: 'Basic pandas manipulation understood, but pipeline automation, unit-level microdata extraction, and API ingestion are unmastered.',
        priority: 'High',
        recommendedActions: ['Enrol in iGOT: Python for Data Science in Public Sector'],
        keyManualsAndStandards: ['MoSPI Open Data Portal API Documentation', 'Python for Official Statistics Handbook'],
        relatedIgotCourseIds: ['igot-c-python-stats'],
      },
      {
        id: 'skill-r',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'R for Survey Estimation & Survey Package',
        currentLevel: 62,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 13,
        aiRationale: 'Proficient in summary statistics; complex survey design weighting using the R `survey` package needs practice.',
        priority: 'Medium',
        recommendedActions: ['Practice with Thomas Lumley survey package tutorials on PLFS microdata'],
        keyManualsAndStandards: ['Complex Surveys: A Guide to Analysis Using R (Thomas Lumley)'],
        relatedIgotCourseIds: ['igot-c-r-stats'],
      },
      {
        id: 'skill-sql',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'SQL & Relational Statistical Database Querying',
        currentLevel: 58,
        requiredLevel: 70,
        gapSeverity: 'improvement_needed',
        gapPercentage: 12,
        aiRationale: 'Basic SELECT queries mastered; window functions, multi-table joins on census blocks, and aggregate grouping require enhancement.',
        priority: 'Medium',
        recommendedActions: ['Complete PostgreSQL query optimization module on iGOT'],
        keyManualsAndStandards: ['MoSPI Microdata Server Database Schema'],
        relatedIgotCourseIds: ['igot-c-sql'],
      },
      {
        id: 'skill-data-viz',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'Data Visualization & Interactive Dashboarding',
        currentLevel: 48,
        requiredLevel: 80,
        gapSeverity: 'critical',
        gapPercentage: 32,
        aiRationale: 'Critical Gap: Modern ministerial reporting requires dynamic charts, PowerBI/Superset dashboards, and accessible infographic generation instead of static tabular PDF releases.',
        priority: 'Critical',
        recommendedActions: ['Priority Enrolment: Data Visualization for Official Statistics (iGOT Karmayogi)'],
        keyManualsAndStandards: ['Government of India Web Guidelines (GIGW) for Visualizations', 'Edward Tufte Visual Display of Quantitative Information'],
        relatedIgotCourseIds: ['igot-c-dataviz-1', 'igot-c-dataviz-2'],
      },
      {
        id: 'skill-aiml',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'AI/ML for Statistical Imputation & Pattern Recognition',
        currentLevel: 42,
        requiredLevel: 75,
        gapSeverity: 'critical',
        gapPercentage: 33,
        aiRationale: 'Critical Gap: Emerging official statistics require machine learning for automated missing data imputation, satellite imagery crop yield estimates, and NLP text classification of economic activities (NIC coding).',
        priority: 'Critical',
        recommendedActions: ['Priority Enrolment: AI & Machine Learning for Statistical Analysis (NSSTA TPAC)'],
        keyManualsAndStandards: ['UN Statistical Commission Big Data / Machine Learning Whitepaper', 'NITI Aayog National Strategy for AI'],
        relatedIgotCourseIds: ['igot-c-aiml-stats'],
      },
      {
        id: 'skill-gis',
        domainId: 'domain-technical',
        domainName: 'Technical Competencies',
        title: 'GIS & Spatial Analytics (QGIS / GeoSpatial Data)',
        currentLevel: 38,
        requiredLevel: 70,
        gapSeverity: 'critical',
        gapPercentage: 32,
        aiRationale: 'Critical Gap: Urban frame survey (UFS) digitization and geo-tagging of enumeration blocks require proficiency in QGIS and shapefile spatial joins.',
        priority: 'Critical',
        recommendedActions: ['Enrol in NSSTA Hands-on GIS in Sample Surveys'],
        keyManualsAndStandards: ['National Geospatial Policy 2022', 'MoSPI Urban Frame Survey Digital Guidelines'],
        relatedIgotCourseIds: ['igot-c-gis'],
      },
    ],
  },
  {
    id: 'domain-digital-gov',
    name: 'Digital Governance',
    code: 'DIGIGOV-DOM',
    color: '#059669', // Emerald
    icon: 'ShieldCheck',
    averageScore: 68,
    requiredBenchmark: 75,
    skills: [
      {
        id: 'skill-cybersecurity',
        domainId: 'domain-digital-gov',
        domainName: 'Digital Governance',
        title: 'Cybersecurity Awareness & CERT-In Guidelines',
        currentLevel: 55,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 20,
        aiRationale: 'Safe data handling, phishing prevention, and adherence to CERT-In cybersecurity mandates for government servers need structured reinforcement.',
        priority: 'High',
        recommendedActions: ['Complete mandatory iGOT Karmayogi Cyber Hygiene certification'],
        keyManualsAndStandards: ['CERT-In Information Security Guidelines for Government Organizations', 'National Cyber Security Policy'],
        relatedIgotCourseIds: ['igot-c-cybersecurity'],
      },
      {
        id: 'skill-data-privacy',
        domainId: 'domain-digital-gov',
        domainName: 'Digital Governance',
        title: 'Data Privacy & Digital Personal Data Protection (DPDP) Act',
        currentLevel: 64,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 16,
        aiRationale: 'Official statistics anonymization rules are known, but compliance obligations as a Data Fiduciary under DPDP Act 2023 require formal upskilling.',
        priority: 'High',
        recommendedActions: ['Study MeitY DPDP Act 2023 implementation handbook for public servants'],
        keyManualsAndStandards: ['Digital Personal Data Protection Act 2023', 'Statistical Confidentiality in the Collection of Statistics Act 2008'],
        relatedIgotCourseIds: ['igot-c-dpdp'],
      },
      {
        id: 'skill-dpi',
        domainId: 'domain-digital-gov',
        domainName: 'Digital Governance',
        title: 'Digital Public Infrastructure (DPI) & MeghRaj Cloud',
        currentLevel: 70,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 5,
        aiRationale: 'Awareness of Aadhaar, UPI, DigiLocker data architectures is sound; practical knowledge of hosting microservices on MeghRaj cloud is emerging.',
        priority: 'Medium',
        recommendedActions: ['Explore National Data and Analytics Platform (NDAP) architecture on iGOT'],
        keyManualsAndStandards: ['GI Cloud (MeghRaj) Guidelines', 'India Enterprise Architecture (IndEA) Framework'],
        relatedIgotCourseIds: ['igot-c-dpi'],
      },
    ],
  },
  {
    id: 'domain-managerial',
    name: 'Behavioural & Managerial Competencies',
    code: 'MGT-DOM',
    color: '#f59e0b', // Amber / Gold
    icon: 'Users',
    averageScore: 74,
    requiredBenchmark: 75,
    skills: [
      {
        id: 'skill-leadership',
        domainId: 'domain-managerial',
        domainName: 'Behavioural & Managerial Competencies',
        title: 'Leadership & Statistical Team Mentoring',
        currentLevel: 72,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 3,
        aiRationale: 'Supervisory skills in field offices are effective; delegating and cross-functional capacity mentoring can be elevated.',
        priority: 'Medium',
        recommendedActions: ['iGOT: Leadership in Civil Service Transformation'],
        keyManualsAndStandards: ['DoPT Civil Service Competency Dictionary'],
        relatedIgotCourseIds: ['igot-c-leadership'],
      },
      {
        id: 'skill-project-mgt',
        domainId: 'domain-managerial',
        domainName: 'Behavioural & Managerial Competencies',
        title: 'Statistical Project Management & Survey Timelines',
        currentLevel: 68,
        requiredLevel: 75,
        gapSeverity: 'improvement_needed',
        gapPercentage: 7,
        aiRationale: 'Survey field schedules often experience lag; adopting Agile and milestone-based project management will enhance timely dissemination.',
        priority: 'Medium',
        recommendedActions: ['Project Management in Government Operations on iGOT'],
        keyManualsAndStandards: ['MoSPI Statistical Survey Project Planning Manual'],
        relatedIgotCourseIds: ['igot-c-project-mgmt'],
      },
      {
        id: 'skill-ethics',
        domainId: 'domain-managerial',
        domainName: 'Behavioural & Managerial Competencies',
        title: 'Ethics, Integrity & Professional Neutrality in Statistics',
        currentLevel: 88,
        requiredLevel: 85,
        gapSeverity: 'strong',
        gapPercentage: -3,
        aiRationale: 'High degree of institutional integrity and steadfast commitment to the UN Fundamental Principles of Official Statistics.',
        priority: 'Low',
        recommendedActions: ['Participate as panelist in NSSTA Statistical Integrity seminars'],
        keyManualsAndStandards: ['UN Fundamental Principles of Official Statistics', 'Civil Services Conduct Rules 1964'],
        relatedIgotCourseIds: ['igot-c-ethics'],
      },
    ],
  },
];

// Mapping to legacy Subject structure for system compatibility
export const initialSubjects: Subject[] = [
  {
    id: 'subj-stat-methods',
    userId: 'user-official-1',
    name: 'Official Statistical Methodologies & Survey Design',
    code: 'STAT-101',
    color: '#3b82f6',
    icon: 'BarChart2',
    targetMarks: 90,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 12 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-stat-1',
        subjectId: 'subj-stat-methods',
        unitNumber: 1,
        title: 'NSS Sampling Design & Field Protocols',
        description: 'Multi-stage stratified sampling, FSU selection, and non-sampling error minimization',
        chapters: [
          {
            id: 'chap-stat-1',
            unitId: 'unit-stat-1',
            chapterNumber: 1,
            title: 'Sample Selection & Multiplier Calculations',
            estimatedBaseHours: 3.0,
            topics: [
              {
                id: 'top-sampling-weights',
                chapterId: 'chap-stat-1',
                title: 'Multiplier Derivation & Weight Calibration',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'High',
                estimatedMins: 45,
                actualMinsSpent: 45,
                masteryPercentage: 82,
                isCompleted: true,
                keyDefinitions: [
                  'First Stage Unit (FSU) Probability of Selection',
                  'Sub-sample multiplier and pooled multiplier formulas',
                ],
              },
              {
                id: 'top-capi-errors',
                chapterId: 'chap-stat-1',
                title: 'CAPI Field Audit & Non-Sampling Error Checks',
                difficulty: 'Hard',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 30,
                masteryPercentage: 64,
                isCompleted: false,
                keyDefinitions: [
                  'Paradata inspection: GPS coordinates, time stamps per question',
                  'Range and consistency checks in digital survey tablets',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-data-viz',
    userId: 'user-official-1',
    name: 'Data Visualization & Dashboarding for Official Statistics',
    code: 'TECH-201',
    color: '#0ea5e9',
    icon: 'PieChart',
    targetMarks: 85,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 18 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-viz-1',
        subjectId: 'subj-data-viz',
        unitNumber: 1,
        title: 'Transforming Tabular Statistical Releases into Visual Insights',
        description: 'Charts, infographics, and interactive dashboard principles for public consumption',
        chapters: [
          {
            id: 'chap-viz-1',
            unitId: 'unit-viz-1',
            chapterNumber: 1,
            title: 'Visual Storytelling for Macroeconomic Indicators',
            estimatedBaseHours: 2.5,
            topics: [
              {
                id: 'top-viz-charts',
                chapterId: 'chap-viz-1',
                title: 'Choropleth Maps & Geospatial Heatmaps for State Disaggregation',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 60,
                actualMinsSpent: 15,
                masteryPercentage: 48,
                isCompleted: false,
                keyDefinitions: [
                  'Classification binning: Natural Breaks (Jenks) vs Equal Intervals',
                  'Color-blind accessible palettes (Cividis/Viridis) for government reports',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-aiml-stats',
    userId: 'user-official-1',
    name: 'AI/ML Applications in Official Statistical Systems',
    code: 'TECH-301',
    color: '#8b5cf6',
    icon: 'Cpu',
    targetMarks: 80,
    creditWeight: 3.5,
    examDate: new Date(Date.now() + 25 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-aiml-1',
        subjectId: 'subj-aiml-stats',
        unitNumber: 1,
        title: 'Machine Learning for Imputation & Satellite Yield Estimation',
        description: 'Automated survey data validation and remote sensing data fusion',
        chapters: [
          {
            id: 'chap-aiml-1',
            unitId: 'unit-aiml-1',
            chapterNumber: 1,
            title: 'Modern Missing Data Imputation Techniques',
            estimatedBaseHours: 3.0,
            topics: [
              {
                id: 'top-imputation-rf',
                chapterId: 'chap-aiml-1',
                title: 'Random Forest & KNN Imputation vs Traditional Mean/Hot-Deck',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 75,
                actualMinsSpent: 10,
                masteryPercentage: 42,
                isCompleted: false,
                keyDefinitions: [
                  'Missing Completely at Random (MCAR) vs Missing at Random (MAR)',
                  'Preserving variance structure in imputed microdata sets',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

// ==============================================================================
// 3. iGOT Karmayogi & NSSTA Recommended Course Catalog
// ==============================================================================

export const initialIGOTCourses: IGOTCourse[] = [
  {
    id: 'igot-c-dataviz-1',
    courseName: 'Data Visualization Fundamentals for Official Statistics',
    provider: 'iGOT Karmayogi',
    competencyDomain: 'Technical Competencies',
    targetedSkill: 'Data Visualization & Interactive Dashboarding',
    durationHours: 6.5,
    difficulty: 'Intermediate',
    description: 'Master the art of translating tabular data from NSS, PLFS, and National Accounts into compelling charts, state choropleth maps, and executive briefs.',
    enrolmentUrl: 'https://igotkarmayogi.gov.in/learn/course/do_31388902',
    completionStatus: 'In Progress',
    progressPercentage: 45,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.9,
    enrolledOfficialsCount: 2450,
    priority: 'Critical',
    reasonRecommended: 'Identified as a critical competency gap (Current: 48% vs Benchmark: 80%) for Senior Statistical Officers.',
    syllabusModules: [
      'Visual Grammar & Chart Selection for Statistical Data',
      'Geospatial Mapping with Open-Source GIS for District Disaggregation',
      'Designing Accessible Dashboards complying with GIGW 3.0 Standards',
      'Hands-on Capstone: Re-imagining MoSPI Annual Report Visuals',
    ],
  },
  {
    id: 'igot-c-aiml-stats',
    courseName: 'AI/ML for Statistical Analysis & Anomaly Detection',
    provider: 'NSSTA TPAC',
    competencyDomain: 'Technical Competencies',
    targetedSkill: 'AI/ML for Statistical Imputation & Pattern Recognition',
    durationHours: 12.0,
    difficulty: 'Advanced',
    description: 'Designed under NSSTA TPAC guidelines for Indian Statistical Service officials: Learn machine learning for missing data imputation, anomaly detection in CPI price submissions, and satellite imagery crop yield estimation.',
    enrolmentUrl: 'https://nssta.gov.in/programmes/tpac-aiml-2026',
    completionStatus: 'Enrolled',
    progressPercentage: 15,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.95,
    enrolledOfficialsCount: 1820,
    priority: 'Critical',
    reasonRecommended: 'Urgent priority gap (Current: 42% vs Benchmark: 75%). Cadre reform mandates AI literacy for macroeconomic forecasting.',
    syllabusModules: [
      'Introduction to Machine Learning in Official Statistics',
      'Advanced Imputation Methods: MICE, KNN, and Random Forest',
      'Natural Language Processing for Automated Industrial & Trade Classification (NIC/HS Code)',
      'Satellite Remote Sensing & Earth Observation Data Fusion for Agriculture',
    ],
  },
  {
    id: 'igot-c-python-stats',
    courseName: 'Python for Official Statistics & Microdata Automation',
    provider: 'iGOT Karmayogi',
    competencyDomain: 'Technical Competencies',
    targetedSkill: 'Python for Official Statistics & Automation',
    durationHours: 8.0,
    difficulty: 'Intermediate',
    description: 'Automate repetitive survey tabulation, conduct rapid validation checks, and query microdata using Pandas, NumPy, and Statsmodels.',
    enrolmentUrl: 'https://igotkarmayogi.gov.in/learn/course/do_3139045',
    completionStatus: 'Not Started',
    progressPercentage: 0,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.85,
    enrolledOfficialsCount: 4120,
    priority: 'High',
    reasonRecommended: 'Required to build robust end-to-end automated pipelines for NSS quarterly releases.',
    syllabusModules: [
      'Pandas for Large-Scale Survey Microdata',
      'Writing Automated Data Quality Validation Scripts',
      'Connecting to Government APIs & PostgreSQL Databases',
      'Generating Automated Dissemination Bulletins with Jupyter & Quarto',
    ],
  },
  {
    id: 'igot-c-national-accounts',
    courseName: 'System of National Accounts (SNA 2008) & Supply-Use Tables',
    provider: 'UNSIAP',
    competencyDomain: 'Statistical Competencies',
    targetedSkill: 'National Accounts (SNA 2008 & GVA Compilation)',
    durationHours: 15.0,
    difficulty: 'Advanced',
    description: 'Jointly developed by UNSIAP and NSSTA for Asian official statistical agencies: Comprehensive coverage of production, income, and capital accounts.',
    enrolmentUrl: 'https://siap-elearning.org/sna-2008',
    completionStatus: 'Completed',
    progressPercentage: 100,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.9,
    enrolledOfficialsCount: 1650,
    priority: 'Medium',
    reasonRecommended: 'Strong competence area; maintain currency with upcoming System of National Accounts 2025 revision.',
    syllabusModules: [
      'Sequence of Accounts in SNA 2008',
      'Balancing Supply and Use Tables (SUT)',
      'Measuring Non-Observed Economy and Informal Sector',
      'Deflators and Real GDP Chain Volume Measures',
    ],
  },
  {
    id: 'igot-c-dpdp',
    courseName: 'Digital Personal Data Protection (DPDP) Act 2023 for Public Officials',
    provider: 'iGOT Karmayogi',
    competencyDomain: 'Digital Governance',
    targetedSkill: 'Data Privacy & Digital Personal Data Protection (DPDP) Act',
    durationHours: 4.0,
    difficulty: 'Foundational',
    description: 'Understand the legal frameworks, anonymization requirements, and fiduciary responsibilities of government data collectors under India’s DPDP Act 2023.',
    enrolmentUrl: 'https://igotkarmayogi.gov.in/learn/course/do_3139811',
    completionStatus: 'Completed',
    progressPercentage: 100,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.8,
    enrolledOfficialsCount: 9400,
    priority: 'High',
    reasonRecommended: 'Mandatory compliance training for all officials handling respondent survey microdata.',
    syllabusModules: [
      'Key Definitions: Data Principal, Data Fiduciary, and Consent Managers',
      'Exemptions for State Functions & Statistical Research',
      'Statistical Disclosure Control (SDC) & Microdata Anonymization Protocols',
      'Penalties and Grievance Redressal Architecture',
    ],
  },
  {
    id: 'igot-c-cybersecurity',
    courseName: 'Cyber Hygiene & CERT-In Compliance for Government Staff',
    provider: 'iGOT Karmayogi',
    competencyDomain: 'Digital Governance',
    targetedSkill: 'Cybersecurity Awareness & CERT-In Guidelines',
    durationHours: 3.5,
    difficulty: 'Foundational',
    description: 'Protect government statistical networks, secure digital signatures, and prevent social engineering attacks.',
    enrolmentUrl: 'https://igotkarmayogi.gov.in/learn/course/do_314012',
    completionStatus: 'In Progress',
    progressPercentage: 60,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.75,
    enrolledOfficialsCount: 15300,
    priority: 'High',
    reasonRecommended: 'Addresses current 55% score in Digital Governance.',
    syllabusModules: [
      'Recognizing Phishing and Spear-Phishing Targeting Civil Servants',
      'Secure Handling of Restricted Statistical Datasets before Release',
      'Multi-Factor Authentication (MFA) & Secure Remote Access (VPN)',
      'Incident Reporting to CERT-In and Ministry CISO',
    ],
  },
];

// ==============================================================================
// 4. Personalized AI Learning Path (Transformed from Study Planner)
// ==============================================================================

const today = new Date();
const todayStr = today.toISOString().split('T')[0];

export const initialScheduleTasks: ScheduleTask[] = [
  {
    id: 'task-lp-1',
    userId: 'user-official-1',
    topicId: 'top-viz-charts',
    subjectId: 'subj-data-viz',
    igotCourseId: 'igot-c-dataviz-1',
    title: 'Data Visualization: Choropleth Maps & Geospatial Heatmaps',
    subjectName: 'Data Visualization & Dashboarding',
    subjectColor: '#0ea5e9',
    taskType: 'igot_course',
    startTime: `${todayStr}T07:15:00`,
    endTime: `${todayStr}T08:15:00`,
    plannedDurationMins: 60,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
    rescheduleReason: 'Recommended by AI: Highest priority critical gap (48% vs 80%) for Senior Statistical Officers.',
  },
  {
    id: 'task-lp-2',
    userId: 'user-official-1',
    topicId: 'top-imputation-rf',
    subjectId: 'subj-aiml-stats',
    igotCourseId: 'igot-c-aiml-stats',
    title: 'AI/ML for Statistics: Missing Data Imputation with Random Forest',
    subjectName: 'AI/ML Applications in Official Statistics',
    subjectColor: '#8b5cf6',
    taskType: 'training_module',
    startTime: `${todayStr}T21:15:00`,
    endTime: `${todayStr}T22:15:00`,
    plannedDurationMins: 60,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
    rescheduleReason: 'Recommended by AI: Priority technical gap (42% vs 75%) required for upcoming PLFS tabulation cycle.',
  },
  {
    id: 'task-lp-3',
    userId: 'user-official-1',
    topicId: 'top-sampling-weights',
    subjectId: 'subj-stat-methods',
    title: 'Diagnostic MCQ Assessment: NSS Multiplier Derivation & Field Protocols',
    subjectName: 'Official Statistical Methodologies',
    subjectColor: '#3b82f6',
    taskType: 'quiz',
    startTime: `${todayStr}T22:15:00`,
    endTime: `${todayStr}T22:30:00`,
    plannedDurationMins: 15,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Medium',
    rescheduleReason: 'Adaptive reassessment to track retention and update competency score.',
  },
];

// ==============================================================================
// 5. Uploaded Training Materials & AI MCQ Generator Repository
// ==============================================================================

export const initialUploadedMaterials: UploadedLearningMaterial[] = [
  {
    id: 'mat-plfs-2025',
    fileName: 'PLFS_Field_Staff_Instruction_Manual_Vol_I.pdf',
    fileType: 'pdf',
    fileSizeMb: 4.8,
    uploadedBy: 'Dr. Sunita Sharma (NSSTA Faculty)',
    uploadDate: '2026-08-10',
    title: 'Periodic Labour Force Survey (PLFS) Field Staff Manual & Concept Handbook',
    targetDomain: 'Statistical Competencies',
    extractedConcepts: [
      'Usual Principal Activity Status (ps)',
      'Subsidiary Economic Activity Status (ss)',
      'Current Weekly Status (CWS)',
      'Worker Population Ratio (WPR)',
      'Labour Force Participation Rate (LFPR)',
      'Rotational Sampling Scheme in Urban Blocks',
    ],
    totalQuestionsGenerated: 24,
    status: 'ready',
    summary: 'Authoritative operational manual detailing the conceptual foundations, concepts of work, and interview protocols for urban and rural sample units across India.',
    documentSnippet: `The Periodic Labour Force Survey (PLFS) adopts a rotational panel sampling design in urban areas. Each selected urban Frame Sampling Unit (FSU) is visited four times in rotation (First Visit and three Re-visits). In rural areas, there is no re-visit and a single visit sample is drawn annually. The activity status of an individual is categorized into: (a) Usual Status (ps+ss) determined on the reference period of preceding 365 days, and (b) Current Weekly Status (CWS) determined on the reference period of preceding 7 days. A person is categorized as employed under CWS if they worked for at least 1 hour on any day during the 7-day reference period.`,
  },
  {
    id: 'mat-sna-gva',
    fileName: 'MoSPI_Sources_and_Methods_National_Accounts_2024.docx',
    fileType: 'docx',
    fileSizeMb: 6.2,
    uploadedBy: 'P. Venkatachalam (MoSPI Admin)',
    uploadDate: '2026-08-18',
    title: 'MoSPI Guidelines on Gross Value Added (GVA) at Basic Prices & Production Tax Deflators',
    targetDomain: 'Statistical Competencies',
    extractedConcepts: [
      'GVA at Basic Prices',
      'Net Product Taxes and Subsidies',
      'GDP at Market Prices formulation',
      'Financial Intermediation Services Indirectly Measured (FISIM)',
      'Consumption of Fixed Capital (CFC)',
    ],
    totalQuestionsGenerated: 18,
    status: 'ready',
    summary: 'Methodological guidebook on estimating national aggregates, compilation of institutional sector accounts, and handling double-deflation in manufacturing indices.',
    documentSnippet: `Gross Domestic Product (GDP) at Market Prices is derived by adding Net Product Taxes (Product Taxes minus Product Subsidies) to Gross Value Added (GVA) at Basic Prices. Basic Prices measure the amount receivable by the producer from the purchaser for a unit of a good or service produced as output, minus any tax payable, and plus any subsidy receivable, as a consequence of its production or sale. GVA = Gross Output at Basic Prices - Intermediate Consumption at Purchasers' Prices.`,
  },
  {
    id: 'mat-aiml-survey',
    fileName: 'UN_Guidelines_Machine_Learning_for_Official_Statistics.pdf',
    fileType: 'pdf',
    fileSizeMb: 3.5,
    uploadedBy: 'Dr. Sunita Sharma (NSSTA Faculty)',
    uploadDate: '2026-08-25',
    title: 'UN Statistical Commission: Modern Machine Learning for Imputation & Remote Sensing',
    targetDomain: 'Technical Competencies',
    extractedConcepts: [
      'Supervised Learning in NIC Code Classification',
      'MissForest Random Forest Imputation',
      'NDVI Spatial Crop Area Prediction',
      'Evaluating Model Explainability and Fairness in Official Publications',
    ],
    totalQuestionsGenerated: 16,
    status: 'ready',
    summary: 'International best practices on incorporating artificial intelligence and predictive modeling within government statistical dissemination pipelines.',
    documentSnippet: `When replacing deterministic rule-based imputation with machine learning algorithms such as Random Forest or Extreme Gradient Boosting, statistical offices must guarantee repeatability and explainability. Microdata releases must clearly distinguish imputed values using standard quality flags. Remote sensing data utilizing Sentinel-2 satellite imagery combined with ground-truth Crop Cutting Experiments (CCEs) provides high-frequency yield forecasts before harvest seasons.`,
  },
];

// ==============================================================================
// 6. Validated AI-Generated Question Bank & Quality Check
// ==============================================================================

export const initialQuizzes: Quiz[] = [
  {
    id: 'quiz-plfs-eval',
    userId: 'user-official-1',
    title: 'Adaptive Assessment: Labour Statistics & PLFS Measurement Standards',
    difficulty: 'Medium',
    competencyDomain: 'Statistical Competencies',
    sourceMaterialName: 'PLFS_Field_Staff_Instruction_Manual_Vol_I.pdf',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-plfs-1',
        questionText: 'Under the Current Weekly Status (CWS) approach in PLFS, what is the minimum duration a person must have worked during the 7-day reference period to be considered employed?',
        questionType: 'mcq',
        options: [
          'At least 1 hour on any day during the 7-day reference period',
          'At least 4 hours on any single day',
          'At least 14 hours across the week',
          'At least half of the normal working week (20 hours)',
        ],
        correctAnswer: 'At least 1 hour on any day during the 7-day reference period',
        explanation: 'According to the official PLFS survey manual and ILO standards, under the Current Weekly Status approach, a person is considered employed if they pursued any economic activity for at least 1 hour on any day of the reference week.',
        topic: 'Labour Statistics & PLFS',
        difficulty: 'Medium',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'PLFS Field Manual Section 2.4 (Concepts of Employment)',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Fully verified against MoSPI PLFS 2024-25 concepts.'],
        },
        status: 'approved',
      },
      {
        id: 'q-plfs-2',
        questionText: 'Which sampling design is employed in the urban frame of the Periodic Labour Force Survey (PLFS)?',
        questionType: 'mcq',
        options: [
          'Simple Random Sampling without Replacement (SRSWOR)',
          'Rotational Panel Sampling with 4 visits per urban Frame Sampling Unit (FSU)',
          'Complete Census Enumeration every quarter',
          'Single-visit stratified sampling without re-interviews',
        ],
        correctAnswer: 'Rotational Panel Sampling with 4 visits per urban Frame Sampling Unit (FSU)',
        explanation: 'In urban areas, PLFS adopts a rotational panel sampling scheme where each selected sample household is visited four times in rotation (First Visit and three Re-visits) to measure quarterly changes in labour market parameters.',
        topic: 'Labour Statistics & PLFS',
        difficulty: 'Hard',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'PLFS Field Manual Chapter 1 (Sampling Design)',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 98,
          notes: ['Accurately differentiates urban rotational panel from rural single-visit scheme.'],
        },
        status: 'approved',
      },
      {
        id: 'q-plfs-3',
        questionText: 'How is the Worker Population Ratio (WPR) mathematically defined in official statistical reports?',
        questionType: 'mcq',
        options: [
          '(Total Unemployed Persons / Labour Force) × 100',
          '(Total Employed Persons / Total Population) × 100',
          '(Labour Force / Total Working-Age Population) × 100',
          '(Total Salaried Workers / Total Informal Workers) × 100',
        ],
        correctAnswer: '(Total Employed Persons / Total Population) × 100',
        explanation: 'Worker Population Ratio (WPR) is defined as the percentage of employed persons in the total population: (Number of employed persons / Total population) * 100.',
        topic: 'Labour Statistics & PLFS',
        difficulty: 'Easy',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'PLFS Analytical Tables Methodology',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Standard indicator definition rigorously validated.'],
        },
        status: 'approved',
      },
      {
        id: 'q-plfs-4',
        questionText: 'Which method is commonly used to select a representative subset from a population in official sample surveys?',
        questionType: 'mcq',
        options: [
          'Data visualization',
          'Sampling',
          'Data encryption',
          'Data cleaning',
        ],
        correctAnswer: 'Sampling',
        explanation: 'Sampling involves selecting a subset of a population for statistical analysis according to probabilistic rules to ensure unbiased representativeness.',
        topic: 'Sampling Theory & Weight Calibration',
        difficulty: 'Easy',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'MoSPI Sampling Standards Chapter 1',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Direct benchmark question matching MoSPI foundational syllabi.'],
        },
        status: 'approved',
      },
    ],
  },
  {
    id: 'quiz-sna-eval',
    userId: 'user-official-1',
    title: 'Diagnostic Assessment: National Accounts & GVA Compilation',
    difficulty: 'Hard',
    competencyDomain: 'Statistical Competencies',
    sourceMaterialName: 'MoSPI_Sources_and_Methods_National_Accounts_2024.docx',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-sna-1',
        questionText: 'What is the precise relationship between Gross Domestic Product (GDP) at Market Prices and Gross Value Added (GVA) at Basic Prices?',
        questionType: 'mcq',
        options: [
          'GDP at Market Prices = GVA at Basic Prices + Product Taxes - Product Subsidies',
          'GDP at Market Prices = GVA at Factor Cost - Production Taxes + Production Subsidies',
          'GDP at Market Prices = GVA at Basic Prices + Net Factor Income from Abroad (NFIA)',
          'GDP at Market Prices = Intermediate Consumption + Gross Capital Formation',
        ],
        correctAnswer: 'GDP at Market Prices = GVA at Basic Prices + Product Taxes - Product Subsidies',
        explanation: 'Under SNA 2008 and India’s headline GDP methodology (Base 2011-12 onwards), GDP at Market Prices = GVA at Basic Prices + Net Product Taxes (Product Taxes minus Product Subsidies).',
        topic: 'National Accounts (SNA 2008)',
        difficulty: 'Hard',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'MoSPI Sources and Methods Chapter 2',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Essential equation in macroeconomic statistics.'],
        },
        status: 'approved',
      },
      {
        id: 'q-sna-2',
        questionText: 'How are production taxes distinguished from product taxes in the 2008 SNA framework?',
        questionType: 'mcq',
        options: [
          'Production taxes are paid per unit of good produced (e.g. GST), whereas product taxes are independent of quantity (e.g. land revenue)',
          'Production taxes are independent of the quantity or value of goods produced (e.g. land revenue, stamp fees), whereas product taxes depend directly on output quantity/value (e.g. GST, excise duty)',
          'Production taxes apply solely to agricultural commodities, while product taxes apply to industrial manufacturing',
          'There is no distinction; both are identical under current Indian compilation standards',
        ],
        correctAnswer: 'Production taxes are independent of the quantity or value of goods produced (e.g. land revenue, stamp fees), whereas product taxes depend directly on output quantity/value (e.g. GST, excise duty)',
        explanation: 'Production taxes (like land revenue, professional tax, stamp duties) are incurred regardless of output volume, whereas product taxes (GST, import duties) vary directly with the quantity or value of goods sold.',
        topic: 'National Accounts (SNA 2008)',
        difficulty: 'Hard',
        competencyDomain: 'Statistical Competencies',
        sourceDocRef: 'MoSPI Sources and Methods Section 3.2',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Distinction regularly tested in official statistical certification exams.'],
        },
        status: 'approved',
      },
    ],
  },
  {
    id: 'quiz-dataviz-eval',
    userId: 'user-official-1',
    title: 'Diagnostic Assessment: Data Visualization & Official Reporting',
    difficulty: 'Medium',
    competencyDomain: 'Technical Competencies',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-viz-1',
        questionText: 'When presenting state-level infant mortality rates or literacy rates, which thematic visual representation is standard in official statistical compendiums?',
        questionType: 'mcq',
        options: [
          '3D Exploded Pie Chart with variable slice heights',
          'Choropleth Map with perceptually uniform sequential color scales and standardized class intervals',
          'Radar Spider Chart with 36 spokes representing states',
          'Dual-axis line chart comparing unrelated cumulative frequencies',
        ],
        correctAnswer: 'Choropleth Map with perceptually uniform sequential color scales and standardized class intervals',
        explanation: 'Choropleth maps with standardized classification intervals (such as natural breaks or quantiles) and accessible color palettes allow rapid, truthful geographic comparison without visual distortion.',
        topic: 'Data Visualization & Dashboarding',
        difficulty: 'Medium',
        competencyDomain: 'Technical Competencies',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 95,
          notes: ['Aligns with MoSPI & GIGW web accessibility standards.'],
        },
        status: 'approved',
      },
    ],
  },
];

// ==============================================================================
// 7. AI Statistical Learning Assistant Personalities
// ==============================================================================

export const initialAITutors: AITutor[] = [
  {
    id: 'assistant-official-stats',
    userId: 'user-official-1',
    name: 'Sankhyiki — Statistical Learning Assistant',
    avatarEmoji: '🏛️',
    personality: 'Rigorous, Methodical & Methodologically Grounded in Indian Official Statistics',
    systemPrompt: `You are Sankhyiki, the specialized AI Statistical Learning Assistant for India's Official Statistical System (MoSPI, DES, NSSTA, and line ministries).
You assist government statisticians and officials in understanding complex concepts, interpreting NSS/PLFS/ASI manuals, analyzing National Accounts formulas, and navigating iGOT Karmayogi capacity building paths.
Guidelines:
1. Always cite relevant Indian statistical manuals (e.g. NSS Survey Instructions, SNA 2008, National Indicator Framework for SDGs, MoSPI Sources & Methods).
2. Provide concise, clear, and mathematically accurate explanations.
3. Contrast traditional statistical methods with modern computational approaches (Python, R, Machine Learning) where relevant.
4. Maintain a respectful, professional civil service tone.`,
    isDefault: true,
    domainFocus: 'Statistical Competencies',
  },
  {
    id: 'assistant-technical-code',
    userId: 'user-official-1',
    name: 'PyStat — Official Statistics Code Mentor',
    avatarEmoji: '💻',
    personality: 'Hands-on, Practical & Code-Centric for Python, R & SQL in Government Surveys',
    systemPrompt: `You are PyStat, an expert code mentor specializing in data pipelines for official statistics using Python (Pandas, Statsmodels), R (survey package), and SQL.
Provide clean, copy-paste ready scripts for reading microdata, computing multipliers, applying post-stratification weights, and generating publication-ready charts.`,
    isDefault: false,
    domainFocus: 'Technical Competencies',
  },
  {
    id: 'assistant-governance',
    userId: 'user-official-1',
    name: 'Nyaya — Governance & Data Privacy Advisor',
    avatarEmoji: '🛡️',
    personality: 'Authoritative & Clear on DPDP Act 2023, Statistical Confidentiality, and Cyber Hygiene',
    systemPrompt: `You are Nyaya, a governance advisor guiding public servants on statistical confidentiality (Collection of Statistics Act 2008), the Digital Personal Data Protection (DPDP) Act 2023, and CERT-In information security mandates.`,
    isDefault: false,
    domainFocus: 'Digital Governance',
  },
];

// ==============================================================================
// 8. Cheatsheets & Reference Guides for Official Statisticians
// ==============================================================================

export const initialCheatsheets: CheatsheetItem[] = [
  {
    id: 'cs-stat-formulas',
    title: 'MoSPI Official Statistical Formulas & Multipliers Quick-Guide',
    subjectName: 'Statistical Competencies',
    subjectColor: '#3b82f6',
    category: 'Sampling & Survey Estimation',
    summary: 'Essential formulas for deriving multipliers in multi-stage stratified sampling, calculating sampling variance, and estimating quarterly urban indicators.',
    keyFormulas: [
      { label: 'Unbiased Estimator of Population Total (Y_hat)', formula: 'Y_hat = ∑ (w_i · y_i) where w_i is the design weight adjusted for non-response.' },
      { label: 'Worker Population Ratio (WPR)', formula: 'WPR = (Total Estimated Employed / Total Estimated Population) × 100' },
      { label: 'Laspeyres Price Index (CPI Base Formula)', formula: 'I_L = (∑ p_t · q_0) / (∑ p_0 · q_0) × 100' },
      { label: 'GDP at Market Prices', formula: 'GDP_mp = GVA_basic + (Product Taxes - Product Subsidies)' },
    ],
    syntaxSnippets: [
      {
        title: 'Computing PLFS Survey Estimates with R Survey Package',
        language: 'r',
        code: `library(survey)\n# Specify two-stage cluster design with stratum and FSU\nplfs_design <- svydesign(\n  id = ~fsu_no + hhid,\n  strata = ~stratum_code,\n  weights = ~multiplier_adjusted,\n  data = plfs_microdata,\n  nest = TRUE\n)\n# Calculate Worker Population Ratio with standard errors\nsvymean(~as.numeric(cws_status %in% c(11, 21, 31, 51)), plfs_design)`,
        note: 'Ensures standard errors properly reflect the complex multi-stage cluster sampling design.',
      },
    ],
    rulesOfThumb: [
      'In rural NSS panels, FSUs are Census villages; in urban panels, FSUs are Urban Frame Survey (UFS) blocks.',
      'Always verify whether multipliers provided in raw microdata are divided by 100 or 200 for sub-sample pooling.',
    ],
    lastUpdated: '2026-08-15',
  },
  {
    id: 'cs-python-microdata',
    title: 'Python for Official Statistical Microdata Analysis Cheatsheet',
    subjectName: 'Technical Competencies',
    subjectColor: '#0ea5e9',
    category: 'Data Science & Automation',
    summary: 'Best practice patterns for loading fixed-width or CSV unit-level survey data, filtering activity codes, and aggregating state aggregates.',
    keyFormulas: [
      { label: 'Weighted Average in Pandas', formula: 'np.average(df["expenditure"], weights=df["weight"])' },
      { label: 'Gini Coefficient Formula', formula: 'Gini = (2 * ∑ (i * y_i)) / (n * ∑ y_i) - (n + 1)/n  (for sorted values)' },
    ],
    syntaxSnippets: [
      {
        title: 'Fast Microdata Aggregation by State and Sector',
        language: 'python',
        code: `import pandas as pd\nimport numpy as np\n\ndef weighted_indicator(group):\n    w = group['multiplier']\n    return pd.Series({\n        'total_pop': w.sum(),\n        'employed': (group['status'].isin([11, 21, 31, 51]) * w).sum(),\n        'wpr': (group['status'].isin([11, 21, 31, 51]) * w).sum() / w.sum() * 100\n    })\n\nsummary = df.groupby(['state_code', 'sector']).apply(weighted_indicator).reset_index()`,
        note: 'High-performance vectorized tabulation suitable for multi-million row Census / NSS microdata.',
      },
    ],
    rulesOfThumb: [
      'Store large microdata in Apache Parquet format rather than raw CSV for 10x query performance.',
      'Check for missing value codes (e.g. 99, 999, or blanks) before computing continuous aggregates.',
    ],
    lastUpdated: '2026-08-20',
  },
];

export const initialLearningResources: LearningResource[] = [
  {
    id: 'res-official-1',
    topicId: 'top-sampling-weights',
    topicTitle: 'Multiplier Derivation & Weight Calibration',
    subjectName: 'Statistical Competencies',
    title: 'Interactive Cheatsheet: MoSPI Multipliers & Survey Estimation',
    resourceType: 'cheatsheet',
    url: '#cheatsheet-stat-formulas',
    difficultyLevel: 'Medium',
    estimatedMins: 15,
    recommendedReason: 'Quick reference guide for understanding probability weighting and sub-sample multiplier pooling in NSS surveys.',
    qualityScore: 5.0,
    sourcePlatform: 'National Statistical Academy Knowledge Bank',
    cheatsheetData: initialCheatsheets[0],
  },
  {
    id: 'res-official-2',
    topicId: 'top-viz-charts',
    topicTitle: 'Choropleth Maps & Geospatial Heatmaps',
    subjectName: 'Technical Competencies',
    title: 'iGOT Course: Data Visualization for Official Statistics',
    resourceType: 'course',
    url: 'https://igotkarmayogi.gov.in',
    difficultyLevel: 'Medium',
    estimatedMins: 60,
    recommendedReason: 'Top AI recommended training module addressing critical capacity gap in visual dissemination.',
    qualityScore: 4.9,
    sourcePlatform: 'iGOT Karmayogi',
  },
  {
    id: 'res-official-3',
    topicId: 'top-imputation-rf',
    topicTitle: 'Modern Missing Data Imputation Techniques',
    subjectName: 'Technical Competencies',
    title: 'UN SIAP Handbook on Machine Learning in Official Statistics',
    resourceType: 'documentation',
    url: 'https://unsiap.org',
    difficultyLevel: 'Hard',
    estimatedMins: 45,
    recommendedReason: 'Comprehensive technical whitepaper on Random Forest imputation for non-response.',
    qualityScore: 4.85,
    sourcePlatform: 'United Nations SIAP',
  },
];

// ==============================================================================
// 9. Workforce Analytics & Heatmap for MoSPI Administrators
// ==============================================================================

export const initialDepartmentMetrics: DepartmentWorkforceMetric[] = [
  {
    departmentId: 'dept-nad',
    departmentName: 'National Accounts Division (NAD)',
    ministry: 'MoSPI',
    totalOfficials: 185,
    averageCompetency: 78,
    trainingCompletionRate: 84,
    criticalGapCount: 18,
    domainScores: {
      statistical: 86,
      technical: 58,
      digitalGovernance: 72,
      behavioural: 76,
    },
    priorityGaps: ['Data Visualization (52%)', 'AI/ML for Forecasting (44%)'],
  },
  {
    departmentId: 'dept-fod',
    departmentName: 'Field Operations Division (FOD - 6 Zonal & 52 Regional Offices)',
    ministry: 'MoSPI',
    totalOfficials: 1420,
    averageCompetency: 69,
    trainingCompletionRate: 72,
    criticalGapCount: 145,
    domainScores: {
      statistical: 76,
      technical: 48,
      digitalGovernance: 65,
      behavioural: 74,
    },
    priorityGaps: ['CAPI Tablet Troubleshooting (51%)', 'QGIS Spatial Block Mapping (36%)', 'Cybersecurity (54%)'],
  },
  {
    departmentId: 'dept-sdrd',
    departmentName: 'Survey Design & Research Division (SDRD, Kolkata)',
    ministry: 'MoSPI',
    totalOfficials: 120,
    averageCompetency: 83,
    trainingCompletionRate: 91,
    criticalGapCount: 8,
    domainScores: {
      statistical: 92,
      technical: 74,
      digitalGovernance: 76,
      behavioural: 81,
    },
    priorityGaps: ['Cloud High-Performance Computing (56%)', 'Big Data Ingestion (60%)'],
  },
  {
    departmentId: 'dept-des-up',
    departmentName: 'Directorate of Economics & Statistics (DES - Uttar Pradesh)',
    ministry: 'State Government DES',
    totalOfficials: 640,
    averageCompetency: 63,
    trainingCompletionRate: 59,
    criticalGapCount: 88,
    domainScores: {
      statistical: 71,
      technical: 44,
      digitalGovernance: 58,
      behavioural: 68,
    },
    priorityGaps: ['Python for Microdata (40%)', 'SDG District Indicator Reporting (52%)', 'Data Privacy DPDP (49%)'],
  },
  {
    departmentId: 'dept-des-mh',
    departmentName: 'Directorate of Economics & Statistics (DES - Maharashtra)',
    ministry: 'State Government DES',
    totalOfficials: 580,
    averageCompetency: 67,
    trainingCompletionRate: 68,
    criticalGapCount: 62,
    domainScores: {
      statistical: 74,
      technical: 52,
      digitalGovernance: 64,
      behavioural: 72,
    },
    priorityGaps: ['Interactive Dashboarding (47%)', 'Price Index Scanner Data (53%)'],
  },
];

// ==============================================================================
// 10. AI Predictive Analytics: Emerging Skills for India's Statistical System
// ==============================================================================

export const initialEmergingSkills: EmergingSkillPrediction[] = [
  {
    id: 'es-1',
    skillName: 'AI & Machine Learning for Official Statistics',
    growthCategory: 'Critical Demand',
    urgencyLevel: 'Immediate (0-6 mo)',
    projectedAdoptionRate: 86,
    primaryDrivers: [
      'MoSPI modernization agenda to accelerate GDP & PLFS releases',
      'Automated satellite imagery processing for agricultural yield statistics',
      'NLP for real-time classification of informal enterprises',
    ],
    recommendedPrograms: [
      'NSSTA TPAC: Certificate in Applied Machine Learning for Official Statistics',
      'iGOT: Python for Data Science in Public Sector',
    ],
    applicableCadres: ['ISS Officers', 'Subordinate Statistical Service (SSS)', 'State DES Cadres'],
  },
  {
    id: 'es-2',
    skillName: 'Geospatial Analytics & QGIS Integration',
    growthCategory: 'Critical Demand',
    urgencyLevel: 'Immediate (0-6 mo)',
    projectedAdoptionRate: 74,
    primaryDrivers: [
      'Digital Urban Frame Survey (UFS) 100% geo-tagging mandate',
      'Small Area Estimation (SAE) combining Census and satellite grids for district level poverty metrics',
    ],
    recommendedPrograms: ['NSSTA Hands-on GIS for Survey Methodologists'],
    applicableCadres: ['Field Operations Staff', 'Survey Research Division', 'State Statistical Bureaus'],
  },
  {
    id: 'es-3',
    skillName: 'MeghRaj Government Cloud & Scalable Data Pipelines',
    growthCategory: 'High Impact',
    urgencyLevel: 'Strategic (6-18 mo)',
    projectedAdoptionRate: 68,
    primaryDrivers: [
      'Migration of National Data and Analytics Platform (NDAP) to high-availability government cloud',
      'API-first automated microdata dissemination replacing static CD/DVD releases',
    ],
    recommendedPrograms: ['iGOT: Cloud Computing Architecture for e-Governance'],
    applicableCadres: ['Computer Centre Division (MoSPI)', 'IT & Systems Officers'],
  },
  {
    id: 'es-4',
    skillName: 'Data Privacy Engineering & Differential Privacy',
    growthCategory: 'High Impact',
    urgencyLevel: 'Strategic (6-18 mo)',
    projectedAdoptionRate: 62,
    primaryDrivers: [
      'Compliance with Digital Personal Data Protection Act 2023',
      'Protecting respondent anonymity in granular synthetic microdata sets',
    ],
    recommendedPrograms: ['iGOT: Statistical Disclosure Control & Data Privacy Engineering'],
    applicableCadres: ['Data Dissemination Officers', 'Senior Statistical Officers'],
  },
  {
    id: 'es-5',
    skillName: 'Big Data & High-Frequency Economic Indicator Ingestion',
    growthCategory: 'Emerging Architecture',
    urgencyLevel: 'Vision 2030',
    projectedAdoptionRate: 58,
    primaryDrivers: [
      'Incorporating GST e-way bills, power consumption, and scanner data into real-time economic trackers',
      'Integration with UN Global Platform for Official Statistics',
    ],
    recommendedPrograms: ['UNSIAP Big Data Foundations for Civil Servants'],
    applicableCadres: ['Economic Statistics Wing', 'National Accounts Division'],
  },
];

// ==============================================================================
// 11. System Notifications, Events & Badges
// ==============================================================================

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-official-1',
    title: '🔴 Critical Competency Gap Identified',
    message: 'AI Evaluation detected Data Visualization (48%) and AI/ML (42%) as priority skill gaps for your current posting in National Accounts.',
    notificationType: 'competency_gap',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-official-1',
    title: 'Recommended iGOT Karmayogi Course Enrolment',
    message: 'Enrol in "Data Visualization Fundamentals for Official Statistics" to advance your competency profile (+18% projected gain).',
    notificationType: 'course_recommended',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-official-1',
    title: 'NSSTA TPAC Assessment Verified',
    message: 'Your recent evaluation in "Sampling Theory & Weight Calibration" was certified at 82% (Exceeds Cadre Benchmark).',
    notificationType: 'achievement',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const initialAcademicEvents: AcademicEvent[] = [
  {
    id: 'event-1',
    userId: 'user-official-1',
    subjectId: 'subj-stat-methods',
    subjectName: 'Official Statistical Methodologies',
    subjectColor: '#3b82f6',
    title: 'Quarterly PLFS Tabulation Readiness Assessment',
    eventType: 'practical',
    eventDate: new Date(Date.now() + 12 * 86400000).toISOString(),
    weightagePercentage: 40,
    syllabusCoverageNeeded: 85,
  },
  {
    id: 'event-2',
    userId: 'user-official-1',
    subjectId: 'subj-data-viz',
    subjectName: 'Data Visualization & Dashboarding',
    subjectColor: '#0ea5e9',
    title: 'iGOT Karmayogi Course Completion Certification Milestone',
    eventType: 'project',
    eventDate: new Date(Date.now() + 18 * 86400000).toISOString(),
    weightagePercentage: 35,
    syllabusCoverageNeeded: 100,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    badgeId: 'nssta-certified',
    title: 'NSSTA Certified Practitioner',
    description: 'Successfully passed National Accounts & Sampling evaluations with >80% score.',
    icon: '🏛️',
    unlockedAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'ach-2',
    badgeId: 'karmayogi-silver',
    title: 'iGOT Karmayogi Scholar',
    description: 'Completed 40+ verified continuous capacity building learning hours.',
    icon: '🇮🇳',
    unlockedAt: '2026-08-20T17:00:00.000Z',
  },
  {
    id: 'ach-3',
    badgeId: 'streak-14',
    title: 'Capacity Building Consistency',
    description: 'Maintained 14 consecutive days of active professional development.',
    icon: '🔥',
    unlockedAt: '2026-08-28T08:00:00.000Z',
  },
];

// Spaced revision items for statistical retention
export const initialSpacedRevisions: SpacedRevision[] = [
  {
    id: 'rev-1',
    userId: 'user-official-1',
    topicId: 'top-sampling-weights',
    topicTitle: 'Multiplier Derivation & Multi-stage Weighting',
    subjectName: 'Statistical Competencies',
    subjectColor: '#3b82f6',
    repetitionNumber: 3,
    easeFactor: 2.6,
    intervalDays: 7,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 4,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rev-2',
    userId: 'user-official-1',
    topicId: 'top-capi-errors',
    topicTitle: 'CAPI Field Audit & Non-Sampling Paradata Checks',
    subjectName: 'Statistical Competencies',
    subjectColor: '#3b82f6',
    repetitionNumber: 1,
    easeFactor: 2.1,
    intervalDays: 2,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 2,
    updatedAt: new Date().toISOString(),
  },
];

// Backward compatibility arena & battle placeholders
export const initialBattleQuestions: BattleQuestion[] = [
  {
    id: 'bq-1',
    subject: 'Official Statistics',
    questionText: 'Under the 2008 SNA, how is Financial Intermediation Services Indirectly Measured (FISIM) allocated?',
    options: ['Directly to Final Consumption', 'Between Intermediate Consumption and Final Consumption using reference rates', 'As a direct subsidy to commercial banks', 'Omitted from GDP calculations'],
    correctAnswer: 'Between Intermediate Consumption and Final Consumption using reference rates',
    explanation: 'FISIM is allocated to user sectors using a reference interest rate representing the pure cost of borrowing.',
    difficulty: 'Hard',
    points: 100,
    timeLimitSec: 20,
  },
];

export const initialChallengers: BattleChallenger[] = [
  {
    id: 'chal-1',
    name: 'Vikram Singh, ISS',
    handle: 'StatOfficer_Vikram',
    avatarEmoji: '📊',
    title: 'Assistant Director (Survey Methodologies)',
    university: 'MoSPI SDRD',
    eloRating: 1850,
    tier: 'Platinum',
    winRate: 78,
    totalBattles: 28,
    wins: 22,
    losses: 6,
    streak: 4,
    favoriteSubject: 'Survey Sampling & Estimation',
    isOnline: true,
  },
];

export const initialLeaderboard: LeaderboardEntry[] = [
  {
    id: 'lead-1',
    rank: 1,
    fullName: 'Rajesh Kumar, ISS',
    handle: 'SSO_RajeshK',
    avatarEmoji: '🏛️',
    university: 'National Accounts Division, MoSPI',
    eloRating: 2150,
    tier: 'Diamond',
    winRate: 86,
    wins: 38,
    losses: 6,
    streak: 7,
    totalXp: 3420,
    subjectBadges: ['National Accounts Pro', 'Sampling Specialist'],
    isCurrentUser: true,
  },
];

export const initialStudentBattleProfile: StudentBattleProfile = {
  id: 'user-official-1',
  fullName: 'Rajesh Kumar, ISS',
  handle: 'SSO_RajeshK',
  avatarEmoji: '🏛️',
  title: 'Senior Statistical Officer',
  university: 'National Accounts Division, MoSPI',
  eloRating: 2150,
  tier: 'Diamond',
  totalBattles: 44,
  wins: 38,
  losses: 6,
  winRate: 86,
  currentStreak: 7,
  bestStreak: 11,
  totalXp: 3420,
  radarStats: [
    { subject: 'National Accounts', score: 84 },
    { subject: 'Survey Sampling', score: 82 },
    { subject: 'Data Quality NQAF', score: 75 },
    { subject: 'R & Python', score: 58 },
    { subject: 'Data Visualization', score: 48 },
  ],
  showcaseBadges: [
    {
      id: 'b-nssta',
      title: 'NSSTA Gold Standard',
      icon: '🏛️',
      rarity: 'Legendary',
      description: 'Maintained top 5% competency score in national macroeconomic tabulation.',
    },
  ],
  recentMatches: [
    {
      id: 'm-1',
      opponentName: 'Vikram Singh, ISS',
      opponentAvatar: '📊',
      opponentTier: 'Platinum',
      userScore: 480,
      opponentScore: 410,
      result: 'Victory',
      eloChange: +24,
      subject: 'National Accounts SNA 2008',
      date: 'Today, 08:30 AM',
    },
  ],
};
