import {
  UserProfile,
  UserAvailability,
  Subject,
  ScheduleTask,
  SpacedRevision,
  AITutor,
  LearningResource,
  Quiz,
  AcademicEvent,
  Achievement,
  NotificationItem,
  CheatsheetItem,
  BattleQuestion,
  BattleChallenger,
  LeaderboardEntry,
  StudentBattleProfile,
  IGOTCourse,
  CompetencyDomain,
  CompetencySkill,
  UploadedLearningMaterial,
  DepartmentWorkforceMetric,
  EmergingSkillPrediction,
} from '@/types';

// ==============================================================================
// 1. College Student Academic Profiles
// ==============================================================================

export const initialProfile: UserProfile = {
  id: 'user-student-1',
  email: 'aarav.sharma@college.edu',
  fullName: 'Aarav Sharma',
  role: 'learner',
  userTrack: 'learner',
  designation: 'B.Tech Computer Science & Engineering (3rd Year / 6th Sem)',
  department: 'Department of Computer Science & Engineering',
  cadre: 'Roll No: 21BCS0842 | Section A',
  currentAssignment: 'End-Semester Exam Prep: OS, DBMS, Networks & DSA',
  jobRole: 'Exam Candidate (Target SGPA: 9.2+ | Current CGPA: 8.7)',
  educationalQualification: 'Class 12 CBSE (94.2%) | B.Tech CSE 5 Semesters Cleared',
  workExperience: '138 Credit Units Cleared | Major: Systems & Software',
  previousTraining: [
    'NPTEL Elite Certificate in Data Structures & Algorithms',
    'Operating Systems Mid-Sem Examination: 28/30',
    'Database Management Systems Lab Practical: Grade A+',
  ],
  completedCourses: [
    'NPTEL: Operating Systems In-Depth & Kernel Architecture',
    'DBMS Relational Query & Normalization Masterclass',
  ],
  currentCompetencyLevels: {
    'Operating Systems': 78,
    'Database Management Systems': 82,
    'Computer Networks': 68,
    'Data Structures & Algorithms': 85,
    'Theory of Computation': 62,
    'Software Engineering': 74,
    'Process Synchronization': 60,
    'Memory Management & Paging': 64,
    'SQL & Query Optimization': 84,
    'Normalization (1NF-BCNF)': 76,
    'TCP/IP & Subnetting': 66,
    'Routing Protocols': 58,
    'Dynamic Programming & Graphs': 72,
    'Discrete Mathematics': 80,
    'Object-Oriented Design': 75,
    'System Architecture': 70,
  },
  overallCompetencyScore: 74,
  dailyMaxStudyHours: 4.0,
  streakDays: 18,
  totalXp: 4150,
  learningHoursLogged: 68.5,
  onboardingCompleted: true,
  createdAt: '2026-01-10T00:00:00.000Z',

  // Backward compatibility fields
  courseDegree: 'B.Tech in Computer Science & Engineering',
  currentSemester: 'Semester 6 (End-Semester Exam Season)',
  targetGpaGrade: 'Target SGPA: 9.2+ / CGPA: 9.0+',
  preferredStudyTime: 'evening',
  pomodoroFocusMins: 45,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const demoTrainerProfile: UserProfile = {
  id: 'user-trainer-1',
  email: 'sunita.sharma@college.edu',
  fullName: 'Dr. Sunita Sharma',
  role: 'trainer',
  designation: 'Professor & Head of Department (Computer Science)',
  department: 'Department of Computer Science & Engineering',
  cadre: 'Faculty ID: FAC-CS-104 | Course Coordinator',
  currentAssignment: 'End-Semester Question Paper Moderation & Syllabus Alignment',
  jobRole: 'Lead Academic Evaluator & Course Coordinator',
  educationalQualification: 'Ph.D. in Computer Science & Engineering (IIT Delhi)',
  workExperience: '18 Years in Academic Teaching, Systems Research & Curriculum Design',
  previousTraining: ['IEEE Computer Society Fellow', 'NPTEL Master Faculty Workshop'],
  completedCourses: ['NPTEL Discipline Star: Computer Science & Engineering'],
  currentCompetencyLevels: {
    'Operating Systems': 98,
    'Database Management Systems': 96,
    'Data Structures & Algorithms': 95,
    'Computer Networks': 92,
    'Theory of Computation': 94,
  },
  overallCompetencyScore: 95,
  dailyMaxStudyHours: 4.0,
  streakDays: 45,
  totalXp: 11200,
  learningHoursLogged: 140.0,
  onboardingCompleted: true,
  createdAt: '2025-08-01T00:00:00.000Z',
  pomodoroFocusMins: 50,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const demoAdminProfile: UserProfile = {
  id: 'user-admin-1',
  email: 'dean.exams@college.edu',
  fullName: 'Prof. P. Venkatachalam',
  role: 'admin',
  designation: 'Dean of Academic Affairs & Controller of Examinations',
  department: 'Office of Controller of Examinations (CoE)',
  cadre: 'Faculty ID: DEAN-ACAD-01',
  currentAssignment: 'End-Semester Exam Schedule, Hall Ticket & Timetable Governance',
  jobRole: 'Controller of Examinations & Academic Dean',
  educationalQualification: 'Ph.D. in Distributed Systems & Information Systems',
  workExperience: '25 Years in University Academic Administration & Examination Governance',
  previousTraining: ['National Board of Accreditation (NBA) Evaluator'],
  completedCourses: ['Higher Education Governance & Outcome-Based Education (OBE)'],
  currentCompetencyLevels: {
    'Operating Systems': 90,
    'System Architecture': 94,
    'Software Engineering': 92,
  },
  overallCompetencyScore: 92,
  dailyMaxStudyHours: 2.0,
  streakDays: 60,
  totalXp: 14500,
  learningHoursLogged: 180.0,
  onboardingCompleted: true,
  createdAt: '2025-05-01T00:00:00.000Z',
  pomodoroFocusMins: 45,
  pomodoroBreakMins: 10,
  longBreakMins: 20,
  stabilityThresholdMins: 15,
};

export const initialAvailability: UserAvailability = {
  userId: 'user-student-1',
  dayType: 'weekday',
  wakeTime: '06:00',
  sleepTime: '23:30',
  institutionHours: '08:30-16:30', // College lectures & laboratory hours
  travelHours: '08:00-08:30, 16:30-17:00', // Campus commute / hostel transit
  mealHours: '07:30-08:00, 12:30-13:30, 20:00-20:45',
  personalActivityHours: '17:00-18:00', // Sports / tea / recharge
  availableStudySlots: [
    { start: '06:30', end: '07:45' }, // Morning high-focus revision before classes
    { start: '18:15', end: '19:45' }, // Post-college problem solving & PYQ practice
    { start: '21:00', end: '23:00' }, // Night deep study slot: intensive exam prep
  ],
};

// ==============================================================================
// 2. The Four College Academic Domains & Exam Competency Skills
// ==============================================================================

export const initialCompetencyDomains: CompetencyDomain[] = [
  {
    id: 'domain-core-cs',
    name: 'Core Computer Science',
    code: 'CORE-CS',
    color: '#3b82f6', // Academic Blue
    icon: 'Cpu',
    averageScore: 74,
    requiredBenchmark: 85,
    skills: [
      {
        id: 'skill-os',
        domainId: 'domain-core-cs',
        domainName: 'Core Computer Science',
        title: 'Operating Systems (Kernel, Scheduling & Virtual Memory)',
        currentLevel: 78,
        requiredLevel: 85,
        gapSeverity: 'improvement_needed',
        gapPercentage: 7,
        aiRationale: 'Strong grasp of CPU scheduling algorithms; process synchronization (Peterson algorithm, semaphores) and Banker deadlock avoidance require numerical problem revision before End-Sem.',
        priority: 'High',
        recommendedActions: ['Complete NPTEL OS Sprint: Process Sync & Deadlocks module', 'Solve 2021-2024 university semester exam papers on Paging'],
        keyManualsAndStandards: ['Silberschatz, Galvin & Gagne: Operating System Concepts (10th Ed)', 'Tanenbaum: Modern Operating Systems'],
        relatedIgotCourseIds: ['exam-c-os-sprint'],
      },
      {
        id: 'skill-dbms',
        domainId: 'domain-core-cs',
        domainName: 'Core Computer Science',
        title: 'Database Management Systems (Relational & NoSQL)',
        currentLevel: 82,
        requiredLevel: 85,
        gapSeverity: 'improvement_needed',
        gapPercentage: 3,
        aiRationale: 'SQL queries and relational algebra are solid; BCNF loss-less join decomposition proofs and B+ Tree node splitting need practice for Section C 15-mark questions.',
        priority: 'High',
        recommendedActions: ['Study Normalization canonical cover algorithm', 'Practice 2-Phase Locking (2PL) conflict serializability graph problems'],
        keyManualsAndStandards: ['Korth, Silberschatz & Sudarshan: Database System Concepts (7th Ed)', 'Elmasri & Navathe: Fundamentals of Database Systems'],
        relatedIgotCourseIds: ['exam-c-dbms-mastery'],
      },
      {
        id: 'skill-networks',
        domainId: 'domain-core-cs',
        domainName: 'Core Computer Science',
        title: 'Computer Networks (OSI, TCP/IP & Protocols)',
        currentLevel: 68,
        requiredLevel: 80,
        gapSeverity: 'critical',
        gapPercentage: 12,
        aiRationale: 'Critical Gap: Numeric subnetting (CIDR/VLSM address blocks) and Distance Vector count-to-infinity problem are frequently asked in semester finals.',
        priority: 'Critical',
        recommendedActions: ['Priority Revision: Subnet mask derivation and IP host range calculation', 'Simulate Dijkstra Link-State and Bellman-Ford algorithms'],
        keyManualsAndStandards: ['Andrew S. Tanenbaum: Computer Networks (6th Ed)', 'Kurose & Ross: Computer Networking: A Top-Down Approach'],
        relatedIgotCourseIds: ['exam-c-cn-protocols'],
      },
      {
        id: 'skill-sys-prog',
        domainId: 'domain-core-cs',
        domainName: 'Core Computer Science',
        title: 'System Programming & Concurrency Architecture',
        currentLevel: 70,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 10,
        aiRationale: 'POSIX threads, mutex locks, and inter-process communication (pipes, shared memory) concepts need reinforcement for the upcoming lab practical examination.',
        priority: 'Medium',
        recommendedActions: ['Review Linux system calls (fork, exec, wait, pipe) in C/C++'],
        keyManualsAndStandards: ['W. Richard Stevens: Advanced Programming in the UNIX Environment'],
        relatedIgotCourseIds: ['exam-c-os-sprint'],
      },
    ],
  },
  {
    id: 'domain-algo-dsa',
    name: 'Algorithms & Problem Solving',
    code: 'ALGO-DSA',
    color: '#8b5cf6', // Indigo / Purple
    icon: 'Code2',
    averageScore: 79,
    requiredBenchmark: 85,
    skills: [
      {
        id: 'skill-dsa-trees',
        domainId: 'domain-algo-dsa',
        domainName: 'Algorithms & Problem Solving',
        title: 'Data Structures (Trees, Graphs & Hash Tables)',
        currentLevel: 85,
        requiredLevel: 85,
        gapSeverity: 'strong',
        gapPercentage: 0,
        aiRationale: 'Excellent conceptual grasp of Binary Search Trees, AVL rotations, and Graph BFS/DFS traversals. Ready for exam section A & B.',
        priority: 'Medium',
        recommendedActions: ['Practice Kruskal and Prim Minimum Spanning Tree edge-relaxation proofs'],
        keyManualsAndStandards: ['CLRS: Introduction to Algorithms (4th Ed)', 'Mark Allen Weiss: Data Structures and Algorithm Analysis'],
        relatedIgotCourseIds: ['exam-c-dsa-pyqs'],
      },
      {
        id: 'skill-dsa-dp',
        domainId: 'domain-algo-dsa',
        domainName: 'Algorithms & Problem Solving',
        title: 'Algorithmic Paradigms (DP, Greedy & Backtracking)',
        currentLevel: 72,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 8,
        aiRationale: 'Greedy algorithms are clear; formulation of Dynamic Programming recurrence relations (0/1 Knapsack, Longest Common Subsequence) needs practice.',
        priority: 'High',
        recommendedActions: ['Solve 5 standard university DP problems: Matrix Chain Multiplication, Coin Change, Edit Distance'],
        keyManualsAndStandards: ['Kleinberg & Tardos: Algorithm Design', 'Striver A-Z DSA Sheet Dynamic Programming'],
        relatedIgotCourseIds: ['exam-c-dsa-pyqs'],
      },
      {
        id: 'skill-dsa-complexity',
        domainId: 'domain-algo-dsa',
        domainName: 'Algorithms & Problem Solving',
        title: 'Asymptotic Complexity Analysis (Big-O, Master Theorem)',
        currentLevel: 82,
        requiredLevel: 85,
        gapSeverity: 'improvement_needed',
        gapPercentage: 3,
        aiRationale: 'Master Theorem for divide-and-conquer recurrences is well-understood; substitution and recursion tree methods need quick formula review.',
        priority: 'Medium',
        recommendedActions: ['Review Master Theorem Case 1, 2 and 3 edge conditions'],
        keyManualsAndStandards: ['CLRS Chapter 3 & 4 (Asymptotic Notation & Recurrences)'],
        relatedIgotCourseIds: ['exam-c-dsa-pyqs'],
      },
    ],
  },
  {
    id: 'domain-theory-cs',
    name: 'Theoretical Computer Science & Math',
    code: 'THEORY-CS',
    color: '#0ea5e9', // Sky Blue
    icon: 'BarChart2',
    averageScore: 71,
    requiredBenchmark: 80,
    skills: [
      {
        id: 'skill-toc',
        domainId: 'domain-theory-cs',
        domainName: 'Theoretical Computer Science & Math',
        title: 'Theory of Computation & Automata (DFA, NFA, TM)',
        currentLevel: 62,
        requiredLevel: 80,
        gapSeverity: 'critical',
        gapPercentage: 18,
        aiRationale: 'Critical Gap: Pumping Lemma proofs for non-regular languages and Context-Free Grammar (Chomsky Normal Form conversion) are guaranteed 20-mark questions.',
        priority: 'Critical',
        recommendedActions: ['Priority Study: Pumping Lemma step-by-step adversary technique', 'Practice DFA state minimization using Table-Filling method'],
        keyManualsAndStandards: ['Michael Sipser: Introduction to the Theory of Computation (3rd Ed)', 'Hopcroft, Motwani & Ullman: Automata Theory, Languages, and Computation'],
        relatedIgotCourseIds: ['exam-c-toc-automata'],
      },
      {
        id: 'skill-discrete-math',
        domainId: 'domain-theory-cs',
        domainName: 'Theoretical Computer Science & Math',
        title: 'Discrete Mathematics (Graph Theory, Logic & Relations)',
        currentLevel: 80,
        requiredLevel: 80,
        gapSeverity: 'strong',
        gapPercentage: 0,
        aiRationale: 'Strong performance in propositional logic, equivalence relations, and Eulerian/Hamiltonian graphs.',
        priority: 'Low',
        recommendedActions: ['Review generating functions and recurrence relation characteristic equations'],
        keyManualsAndStandards: ['Kenneth H. Rosen: Discrete Mathematics and Its Applications (8th Ed)'],
        relatedIgotCourseIds: ['exam-c-toc-automata'],
      },
    ],
  },
  {
    id: 'domain-dev-systems',
    name: 'Software Engineering & Web Systems',
    code: 'DEV-SYSTEMS',
    color: '#10b981', // Emerald
    icon: 'Layers',
    averageScore: 75,
    requiredBenchmark: 80,
    skills: [
      {
        id: 'skill-se-agile',
        domainId: 'domain-dev-systems',
        domainName: 'Software Engineering & Web Systems',
        title: 'Software Engineering, UML Diagrams & Testing',
        currentLevel: 74,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 6,
        aiRationale: 'SDLC models (Agile, Waterfall) and Cyclomatic Complexity calculations are clear; UML Sequence diagrams and Design Patterns (Singleton, Factory) need review.',
        priority: 'Medium',
        recommendedActions: ['Practice drawing Class and Sequence diagrams for university case studies (ATM / Library Management)'],
        keyManualsAndStandards: ['Roger S. Pressman: Software Engineering: A Practitioner’s Approach', 'Ian Sommerville: Software Engineering'],
        relatedIgotCourseIds: ['exam-c-se-agile'],
      },
      {
        id: 'skill-web-api',
        domainId: 'domain-dev-systems',
        domainName: 'Software Engineering & Web Systems',
        title: 'Full-Stack Web Architectures & RESTful APIs',
        currentLevel: 76,
        requiredLevel: 80,
        gapSeverity: 'improvement_needed',
        gapPercentage: 4,
        aiRationale: 'Good practical knowledge of React, Next.js, and HTTP status codes; review CORS, JWT auth headers, and web security before viva.',
        priority: 'Medium',
        recommendedActions: ['Review HTTP methods, idempotency, and REST API architectural constraints'],
        keyManualsAndStandards: ['MDN Web Docs Architecture Guides', 'Clean Architecture by Robert C. Martin'],
        relatedIgotCourseIds: ['exam-c-se-agile'],
      },
    ],
  },
];

// Mapping to legacy Subject structure for system compatibility
export const initialSubjects: Subject[] = [
  {
    id: 'subj-os-systems',
    userId: 'user-student-1',
    name: 'Operating Systems & System Architecture',
    code: 'CS-OS-301',
    color: '#3b82f6',
    icon: 'Cpu',
    targetMarks: 90,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 12 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-os-1',
        subjectId: 'subj-os-systems',
        unitNumber: 1,
        title: 'Process Management, Scheduling & Synchronization',
        description: 'CPU scheduling algorithms, critical section solutions, semaphores, and classic synchronization problems.',
        chapters: [
          {
            id: 'chap-os-1',
            unitId: 'unit-os-1',
            chapterNumber: 1,
            title: 'Critical Section, Mutex & Semaphores',
            estimatedBaseHours: 3.0,
            topics: [
              {
                id: 'top-os-semaphores',
                chapterId: 'chap-os-1',
                title: 'Critical Section Problem, Mutex Locks & Semaphores',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 45,
                masteryPercentage: 60,
                isCompleted: false,
                keyDefinitions: [
                  'Mutual Exclusion, Progress, and Bounded Waiting conditions',
                  'Counting Semaphores vs Binary Semaphores (Wait/Signal primitives)',
                  'Producer-Consumer and Readers-Writers synchronization',
                ],
              },
              {
                id: 'top-os-deadlocks',
                chapterId: 'chap-os-1',
                title: 'Deadlock Characterization, Prevention & Banker’s Algorithm',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 30,
                masteryPercentage: 65,
                isCompleted: false,
                keyDefinitions: [
                  'Four Necessary Conditions: Mutual exclusion, Hold & wait, No preemption, Circular wait',
                  'Resource-Allocation Graph (RAG) cycle detection',
                  'Banker’s Safety Algorithm and Resource-Request Algorithm',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-dbms-sql',
    userId: 'user-student-1',
    name: 'Database Management Systems (DBMS)',
    code: 'CS-DBMS-302',
    color: '#0ea5e9',
    icon: 'Database',
    targetMarks: 92,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 15 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-dbms-1',
        subjectId: 'subj-dbms-sql',
        unitNumber: 2,
        title: 'Relational Schema, Normalization & Query Processing',
        description: 'Functional dependencies, 1NF to BCNF decomposition, loss-less joins, and complex SQL joins.',
        chapters: [
          {
            id: 'chap-dbms-1',
            unitId: 'unit-dbms-1',
            chapterNumber: 1,
            title: 'Functional Dependencies & Normal Forms (1NF-BCNF)',
            estimatedBaseHours: 3.5,
            topics: [
              {
                id: 'top-dbms-bcnf',
                chapterId: 'chap-dbms-1',
                title: 'Functional Dependency Closure, Canonical Cover & BCNF Proofs',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 45,
                masteryPercentage: 76,
                isCompleted: false,
                keyDefinitions: [
                  'Closure of Attribute Sets (X+) and Minimal Canonical Cover derivation',
                  'Boyce-Codd Normal Form (BCNF) condition: α → β where α is superkey',
                  'Lossless-Join Decomposition check and Dependency Preservation test',
                ],
              },
              {
                id: 'top-dbms-sql-queries',
                chapterId: 'chap-dbms-1',
                title: 'Advanced SQL: Window Functions, Correlated Subqueries & Triggers',
                difficulty: 'Medium',
                importance: 'High',
                knowledgeLevel: 'High',
                estimatedMins: 45,
                actualMinsSpent: 45,
                masteryPercentage: 84,
                isCompleted: true,
                keyDefinitions: [
                  'GROUP BY with HAVING vs WHERE clause evaluation order',
                  'OVER (PARTITION BY ... ORDER BY ...) window aggregations',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-networks-tcp',
    userId: 'user-student-1',
    name: 'Computer Networks & Internet Protocols',
    code: 'CS-CN-303',
    color: '#8b5cf6',
    icon: 'Layers',
    targetMarks: 85,
    creditWeight: 3.5,
    examDate: new Date(Date.now() + 19 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-cn-1',
        subjectId: 'subj-networks-tcp',
        unitNumber: 3,
        title: 'Network Layer, Subnetting & Routing Algorithms',
        description: 'IPv4/IPv6 addressing, CIDR, VLSM subnetting, Dijkstra and Bellman-Ford routing algorithms.',
        chapters: [
          {
            id: 'chap-cn-1',
            unitId: 'unit-cn-1',
            chapterNumber: 1,
            title: 'IP Addressing, CIDR Subnetting & Routing Protocols',
            estimatedBaseHours: 3.5,
            topics: [
              {
                id: 'top-cn-subnetting',
                chapterId: 'chap-cn-1',
                title: 'CIDR Subnetting, Network Masking & Host Range Calculation',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 60,
                actualMinsSpent: 20,
                masteryPercentage: 58,
                isCompleted: false,
                keyDefinitions: [
                  'Classless Inter-Domain Routing (CIDR) prefix notation (/24, /26, /28)',
                  'Subnet Network Address, First/Last Usable Host, and Broadcast Address',
                  'Variable Length Subnet Masking (VLSM) hierarchical allocation',
                ],
              },
              {
                id: 'top-cn-routing',
                chapterId: 'chap-cn-1',
                title: 'Routing Algorithms: Distance Vector (Bellman-Ford) vs Link State (Dijkstra)',
                difficulty: 'Hard',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 60,
                actualMinsSpent: 30,
                masteryPercentage: 66,
                isCompleted: false,
                keyDefinitions: [
                  'Distance Vector: Bellman-Ford equation, count-to-infinity problem, split horizon',
                  'Link State: Dijkstra shortest path computation, flooding of Link State Advertisements (LSA)',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-dsa-algorithms',
    userId: 'user-official-1',
    name: 'Data Structures & Algorithms (DSA Mastery)',
    code: 'CS-DSA-401',
    color: '#10b981',
    icon: 'Code',
    targetMarks: 95,
    creditWeight: 4.5,
    examDate: new Date(Date.now() + 30 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-dsa-1',
        subjectId: 'subj-dsa-algorithms',
        unitNumber: 1,
        title: 'Core Data Structures: Arrays, Trees, Graphs & Dynamic Programming',
        description: 'Time & space complexity analysis (Big-O), memory models, recursive backtracking, and optimal graph traversals.',
        chapters: [
          {
            id: 'chap-dsa-1',
            unitId: 'unit-dsa-1',
            chapterNumber: 1,
            title: 'Linear Data Structures & Two-Pointer / Sliding Window Techniques',
            estimatedBaseHours: 3.5,
            topics: [
              {
                id: 'top-arrays-hash',
                chapterId: 'chap-dsa-1',
                title: 'Arrays, Hash Maps & Two-Pointer Search Patterns',
                difficulty: 'Medium',
                importance: 'Critical',
                knowledgeLevel: 'Medium',
                estimatedMins: 45,
                actualMinsSpent: 20,
                masteryPercentage: 65,
                isCompleted: false,
                keyDefinitions: [
                  'Two-Sum & 3-Sum optimal O(N) hash map lookups vs O(N log N) sorting',
                  'Sliding window maximums and substring constraints',
                ],
              },
              {
                id: 'top-linked-lists',
                chapterId: 'chap-dsa-1',
                title: 'Linked Lists, Stacks, Queues & Monotonic Stacks',
                difficulty: 'Medium',
                importance: 'High',
                knowledgeLevel: 'Medium',
                estimatedMins: 50,
                actualMinsSpent: 10,
                masteryPercentage: 60,
                isCompleted: false,
                keyDefinitions: [
                  'Fast & slow pointer (Floyd’s cycle detection) algorithm',
                  'Next greater element using monotonic decreasing stack in O(N)',
                ],
              },
            ],
          },
          {
            id: 'chap-dsa-2',
            unitId: 'unit-dsa-1',
            chapterNumber: 2,
            title: 'Trees, Heaps, Graphs & Shortest Path Algorithms',
            estimatedBaseHours: 4.0,
            topics: [
              {
                id: 'top-trees-bst',
                chapterId: 'chap-dsa-2',
                title: 'Binary Search Trees (BST), AVL Balancing & Tree Traversals',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 60,
                actualMinsSpent: 15,
                masteryPercentage: 45,
                isCompleted: false,
                keyDefinitions: [
                  'In-order, Pre-order, Post-order and Level-Order (BFS) traversals',
                  'Lowest Common Ancestor (LCA) in binary trees',
                ],
              },
              {
                id: 'top-graphs-dijkstra',
                chapterId: 'chap-dsa-2',
                title: 'Graph Traversals (BFS/DFS), Topological Sort & Dijkstra’s Algorithm',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 75,
                actualMinsSpent: 10,
                masteryPercentage: 40,
                isCompleted: false,
                keyDefinitions: [
                  'Dijkstra’s shortest path with min-heap priority queue in O((V + E) log V)',
                  'Kahn’s algorithm for cycle detection and dependency resolution',
                ],
              },
            ],
          },
          {
            id: 'chap-dsa-3',
            unitId: 'unit-dsa-1',
            chapterNumber: 3,
            title: 'Dynamic Programming & Recursive Memoization',
            estimatedBaseHours: 4.5,
            topics: [
              {
                id: 'top-dp-patterns',
                chapterId: 'chap-dsa-3',
                title: '0/1 Knapsack, Longest Common Subsequence (LCS) & State Transitions',
                difficulty: 'Hard',
                importance: 'Critical',
                knowledgeLevel: 'Low',
                estimatedMins: 90,
                actualMinsSpent: 0,
                masteryPercentage: 35,
                isCompleted: false,
                keyDefinitions: [
                  'Overlapping subproblems and optimal substructure formulation',
                  'Space optimization from 2D table to 1D rolling array',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'subj-fullstack-dev',
    userId: 'user-official-1',
    name: 'Modern Full-Stack Engineering & Clean Code',
    code: 'CS-ENG-302',
    color: '#6366f1',
    icon: 'Terminal',
    targetMarks: 90,
    creditWeight: 4.0,
    examDate: new Date(Date.now() + 35 * 86400000).toISOString().split('T')[0],
    units: [
      {
        id: 'unit-eng-1',
        unitNumber: 1,
        subjectId: 'subj-fullstack-dev',
        title: 'TypeScript, Modern React & Asynchronous Architecture',
        description: 'Type safety, state machines, REST/GraphQL APIs, concurrency models, and resilient backend systems.',
        chapters: [
          {
            id: 'chap-eng-1',
            unitId: 'unit-eng-1',
            chapterNumber: 1,
            title: 'TypeScript Systems, Generics & System Design Principles',
            estimatedBaseHours: 3.0,
            topics: [
              {
                id: 'top-ts-generics',
                chapterId: 'chap-eng-1',
                title: 'TypeScript Advanced Types, Generics & Utility Helpers',
                difficulty: 'Medium',
                importance: 'High',
                knowledgeLevel: 'High',
                estimatedMins: 45,
                actualMinsSpent: 45,
                masteryPercentage: 80,
                isCompleted: true,
                keyDefinitions: [
                  'Discriminated unions, type narrowing and exhaustiveness checks',
                  'Generic constraints and conditional types (Infer keyword)',
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];

// ==============================================================================
// 3. College Exam Preparation & University Syllabus Course Catalog
// ==============================================================================

export const initialIGOTCourses: IGOTCourse[] = [
  {
    id: 'exam-c-os-sprint',
    courseName: 'Operating Systems End-Sem Sprint: Process Sync, Deadlocks & Memory Management',
    provider: 'NPTEL / SWAYAM',
    competencyDomain: 'Core Computer Science',
    targetedSkill: 'Operating Systems (Kernel, Scheduling & Virtual Memory)',
    durationHours: 6.0,
    difficulty: 'Intermediate',
    description: 'Complete high-yield revision covering Peterson algorithm, Semaphores, Banker algorithm for Deadlocks, Paging, and Page Replacement (FIFO, LRU, Optimal).',
    enrolmentUrl: 'https://nptel.ac.in/courses/106106144',
    completionStatus: 'In Progress',
    progressPercentage: 55,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.9,
    enrolledOfficialsCount: 4850,
    priority: 'Critical',
    reasonRecommended: 'End-Sem Exam in 12 days. High weightage unit: 32 marks in previous university question papers.',
    syllabusModules: [
      'Unit 1: Process Management & CPU Scheduling (FCFS, SJF, Round Robin)',
      'Unit 2: Inter-Process Communication, Mutex & Classical Sync Problems',
      'Unit 3: Deadlock Characterization, Prevention & Banker Algorithm',
      'Unit 4: Virtual Memory, Demand Paging & Inverted Page Tables',
    ],
  },
  {
    id: 'exam-c-dbms-mastery',
    courseName: 'DBMS University Exam Booster: SQL, Normalization (1NF to BCNF) & Concurrency',
    provider: 'IIT Madras / NPTEL',
    competencyDomain: 'Core Computer Science',
    targetedSkill: 'Database Management Systems (Relational & NoSQL)',
    durationHours: 5.5,
    difficulty: 'Intermediate',
    description: 'Master functional dependencies, loss-less join decomposition, BCNF proofs, B+ Trees indexing, 2-Phase Locking (2PL), and ACID serializability.',
    enrolmentUrl: 'https://nptel.ac.in/courses/106106093',
    completionStatus: 'Enrolled',
    progressPercentage: 20,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.95,
    enrolledOfficialsCount: 5200,
    priority: 'Critical',
    reasonRecommended: 'Exam Question Alert: Normalization proofs are mandatory 15-mark questions in Section C.',
    syllabusModules: [
      'Unit 1: Relational Algebra & Advanced SQL Group-By Queries',
      'Unit 2: Functional Dependencies & Closure Canonical Covers',
      'Unit 3: Normal Forms: 1NF, 2NF, 3NF and BCNF Decomposition',
      'Unit 4: Transaction Concurrency Control, Conflict Serializability & WAL',
    ],
  },
  {
    id: 'exam-c-cn-protocols',
    courseName: 'Computer Networks Fast-Track: TCP/IP, IP Addressing, Subnetting & Routing',
    provider: 'Stanford / NPTEL',
    competencyDomain: 'Core Computer Science',
    targetedSkill: 'Computer Networks (OSI, TCP/IP & Protocols)',
    durationHours: 7.0,
    difficulty: 'Intermediate',
    description: 'Crack numeric subnetting questions (CIDR / VLSM), Distance Vector vs Link State routing (Dijkstra), TCP 3-way handshake, flow control, and DNS/HTTP.',
    enrolmentUrl: 'https://onlinecourses.nptel.ac.in/noc23_cs38',
    completionStatus: 'Not Started',
    progressPercentage: 0,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.88,
    enrolledOfficialsCount: 4120,
    priority: 'High',
    reasonRecommended: 'Addresses weak topic in Subnetting calculation (Current test score: 58% vs Target: 80%).',
    syllabusModules: [
      'Unit 1: Physical & Data Link Layer: Framing, CRC & Sliding Window Protocols',
      'Unit 2: Network Layer: IPv4/IPv6, CIDR Subnetting & NAT',
      'Unit 3: Routing Protocols: RIP, OSPF, BGP and Distance Vector Bellman-Ford',
      'Unit 4: Transport Layer: TCP Flow Control, Congestion Control & UDP',
    ],
  },
  {
    id: 'exam-c-dsa-pyqs',
    courseName: 'Data Structures & Algorithms: Semester PYQs & Pattern Mastery',
    provider: 'University Syllabus',
    competencyDomain: 'Algorithms & Problem Solving',
    targetedSkill: 'Data Structures (Trees, Graphs & Hash Tables)',
    durationHours: 8.5,
    difficulty: 'Advanced',
    description: 'Comprehensive walkthrough of previous 5 years university exam papers: AVL tree rotations, Dijkstra algorithm, Dynamic Programming knapsack variants, and Graph traversals.',
    enrolmentUrl: 'https://takeuforward.org/strivers-a2z-dsa-course/',
    completionStatus: 'Completed',
    progressPercentage: 100,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.96,
    enrolledOfficialsCount: 8600,
    priority: 'High',
    reasonRecommended: 'Core syllabus completed; maintain speed with daily 30-minute practice.',
    syllabusModules: [
      'Unit 1: Non-Linear Data Structures: Binary Search Trees & AVL Rotations',
      'Unit 2: Priority Queues & Binary Heaps (Min/Max Heapify)',
      'Unit 3: Graph Algorithms: BFS, DFS, Kruskal & Prim MST',
      'Unit 4: Dynamic Programming: 0/1 Knapsack, LCS & Coin Change',
    ],
  },
  {
    id: 'exam-c-toc-automata',
    courseName: 'Theory of Computation: DFA/NFA, Regular Expressions & Turing Machines',
    provider: 'MIT OpenCourseWare',
    competencyDomain: 'Theoretical Computer Science & Math',
    targetedSkill: 'Theory of Computation & Automata (DFA, NFA, TM)',
    durationHours: 6.0,
    difficulty: 'Hard',
    description: 'Step-by-step constructions for DFA minimization, Myhill-Nerode, Pumping Lemma for Regular & Context-Free Languages, and Halting Problem reduction.',
    enrolmentUrl: 'https://ocw.mit.edu/courses/18-404j-theory-of-computation-fall-2020/',
    completionStatus: 'In Progress',
    progressPercentage: 40,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.92,
    enrolledOfficialsCount: 3400,
    priority: 'High',
    reasonRecommended: 'Pumping Lemma proofs frequently carry 10-15 marks in university finals.',
    syllabusModules: [
      'Unit 1: Deterministic & Non-Deterministic Finite Automata (DFA/NFA)',
      'Unit 2: Regular Expressions, Arden Theorem & DFA Minimization',
      'Unit 3: Context-Free Grammars, Chomsky Normal Form (CNF) & Pushdown Automata',
      'Unit 4: Turing Machines, Church-Turing Thesis & Undecidability',
    ],
  },
  {
    id: 'exam-c-se-agile',
    courseName: 'Software Engineering & System Architecture: UML, Design Patterns & Testing',
    provider: 'Coursera Academic',
    competencyDomain: 'Software Engineering & Web Systems',
    targetedSkill: 'Software Engineering, UML Diagrams & Testing',
    durationHours: 4.0,
    difficulty: 'Foundational',
    description: 'Software development life cycles (SDLC), Agile Scrum rituals, UML Class/Sequence diagrams, Black-box/White-box testing, and Clean Architecture.',
    enrolmentUrl: 'https://www.coursera.org/learn/software-engineering',
    completionStatus: 'Completed',
    progressPercentage: 100,
    isNsstaRecommended: true,
    tpacAccredited: true,
    rating: 4.82,
    enrolledOfficialsCount: 7100,
    priority: 'Medium',
    reasonRecommended: 'Solid grasp of design principles (Current score: 82%); review UML diagrams before viva.',
    syllabusModules: [
      'Unit 1: Software Process Models: Waterfall, Spiral, Agile & Scrum',
      'Unit 2: Requirements Engineering & Use Case Modeling',
      'Unit 3: UML Class, Sequence and State Transition Diagrams',
      'Unit 4: Software Testing: Cyclomatic Complexity, Equivalence Partitioning & BVA',
    ],
  },
];

// ==============================================================================
// 4. Personalized AI Study Timetable (Aligned with College Lectures & Exam Dates)
// ==============================================================================

const today = new Date();
const todayStr = today.toISOString().split('T')[0];

export const initialScheduleTasks: ScheduleTask[] = [
  {
    id: 'task-lp-1',
    userId: 'user-student-1',
    topicId: 'top-os-semaphores',
    subjectId: 'subj-os-systems',
    igotCourseId: 'exam-c-os-sprint',
    title: 'Operating Systems: Critical Section, Mutex & Semaphores',
    subjectName: 'Operating Systems & System Architecture',
    subjectColor: '#3b82f6',
    taskType: 'study',
    startTime: `${todayStr}T06:30:00`,
    endTime: `${todayStr}T07:45:00`,
    plannedDurationMins: 75,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
    rescheduleReason: 'Morning focus slot before college: High-weightage unit for upcoming End-Sem Exam.',
  },
  {
    id: 'task-lp-2',
    userId: 'user-student-1',
    topicId: 'top-dbms-bcnf',
    subjectId: 'subj-dbms-sql',
    igotCourseId: 'exam-c-dbms-mastery',
    title: 'DBMS: Practice BCNF Decomposition Proofs & SQL Window Functions',
    subjectName: 'Database Management Systems (DBMS)',
    subjectColor: '#0ea5e9',
    taskType: 'practice',
    startTime: `${todayStr}T18:15:00`,
    endTime: `${todayStr}T19:30:00`,
    plannedDurationMins: 75,
    status: 'pending',
    isLocked: false,
    priorityTag: 'Critical',
    rescheduleReason: 'Post-lecture problem solving: 15-mark compulsory question in Unit 2.',
  },
  {
    id: 'task-lp-3',
    userId: 'user-student-1',
    topicId: 'top-cn-subnetting',
    subjectId: 'subj-networks-tcp',
    igotCourseId: 'exam-c-cn-protocols',
    title: 'Computer Networks: CIDR Subnetting Calculations & Routing Simulation',
    subjectName: 'Computer Networks & Internet Protocols',
    subjectColor: '#8b5cf6',
    taskType: 'revision',
    startTime: `${todayStr}T21:15:00`,
    endTime: `${todayStr}T22:30:00`,
    plannedDurationMins: 75,
    status: 'pending',
    isLocked: false,
    priorityTag: 'High',
    rescheduleReason: 'Night revision slot: Spaced repetition for numeric formulas and network masks.',
  },
  {
    id: 'task-lp-4',
    userId: 'user-student-1',
    topicId: 'top-os-deadlocks',
    subjectId: 'subj-os-systems',
    igotCourseId: 'exam-c-os-sprint',
    title: 'End-Sem MCQ Speed Drill: 20 Questions on OS & DBMS',
    subjectName: 'Operating Systems & System Architecture',
    subjectColor: '#3b82f6',
    taskType: 'quiz',
    startTime: `${todayStr}T22:30:00`,
    endTime: `${todayStr}T22:50:00`,
    plannedDurationMins: 20,
    status: 'pending',
    isLocked: false,
    priorityTag: 'High',
    rescheduleReason: 'Timed exam drill to build question-solving speed for 3-hour university theory paper.',
  },
];

// ==============================================================================
// 5. Uploaded Semester Exam Materials & AI Question Bank Repository
// ==============================================================================

export const initialUploadedMaterials: UploadedLearningMaterial[] = [
  {
    id: 'mat-os-syllabus',
    fileName: 'Operating_Systems_University_Syllabus_Units_1_to_4.pdf',
    fileType: 'pdf',
    fileSizeMb: 5.2,
    uploadedBy: 'Dr. Sunita Sharma (HOD / Course Coordinator)',
    uploadDate: '2026-02-10',
    title: 'Operating Systems Course Handbook & Classical Synchronization Problems',
    targetDomain: 'Core Computer Science',
    extractedConcepts: [
      'Process States & PCB',
      'Peterson Algorithm',
      'Semaphores & Mutex Primitives',
      'Banker Algorithm for Deadlock Avoidance',
      'Virtual Memory & Demand Paging',
      'Page Replacement Algorithms (LRU, FIFO, Optimal)',
    ],
    totalQuestionsGenerated: 24,
    status: 'ready',
    summary: 'Comprehensive university syllabus pack covering process scheduling, synchronization primitives, deadlocks, and memory hierarchy.',
    documentSnippet: `A critical section is a piece of code that accesses shared resources. A valid synchronization solution must satisfy Mutual Exclusion, Progress, and Bounded Waiting. Semaphores provide wait() and signal() atomic operations. Banker algorithm avoids deadlocks by ensuring the system remains in a safe state where a safe execution sequence of processes exists. In virtual memory, page faults trigger demand paging, swapping required frames from disk into physical memory.`,
  },
  {
    id: 'mat-dbms-pyq',
    fileName: 'DBMS_University_Previous_Year_Questions_2020_2025.pdf',
    fileType: 'pdf',
    fileSizeMb: 4.6,
    uploadedBy: 'Department of Computer Science & Engineering',
    uploadDate: '2026-02-18',
    title: 'DBMS University Exam Question Bank & Normalization Proofs',
    targetDomain: 'Core Computer Science',
    extractedConcepts: [
      'Functional Dependencies & Closure X+',
      'Minimal Canonical Cover',
      'Normal Forms: 1NF, 2NF, 3NF and BCNF',
      'Lossless-Join Decomposition & Dependency Preservation',
      'ACID Properties & Conflict Serializability',
      'Two-Phase Locking Protocol (2PL)',
    ],
    totalQuestionsGenerated: 22,
    status: 'ready',
    summary: 'Previous 5 years semester examination papers with step-by-step normal form proofs and relational algebra solutions.',
    documentSnippet: `A relational schema R is in Boyce-Codd Normal Form (BCNF) with respect to a set of functional dependencies F if, for all functional dependencies in F+ of the form α → β, where α ⊆ R and β ⊆ R, at least one of the following holds: α → β is trivial (i.e. β ⊆ α), or α is a superkey for R. A decomposition is lossless-join if R1 ∩ R2 → R1 or R1 ∩ R2 → R2. In transactions, Two-Phase Locking (Growing and Shrinking phase) guarantees conflict serializability.`,
  },
  {
    id: 'mat-cn-guide',
    fileName: 'Computer_Networks_Subnetting_and_Protocols_Handbook.pdf',
    fileType: 'pdf',
    fileSizeMb: 3.8,
    uploadedBy: 'Prof. P. Venkatachalam (Dean / CoE)',
    uploadDate: '2026-02-25',
    title: 'Computer Networks Semester Exam Guide: IP Subnetting & Routing Algorithms',
    targetDomain: 'Core Computer Science',
    extractedConcepts: [
      'CIDR Subnetting & VLSM Allocation',
      'Dijkstra Link-State Algorithm',
      'Distance Vector (Bellman-Ford) Routing',
      'Count-to-Infinity & Split Horizon',
      'TCP 3-Way Handshake & Flow Control',
      'Sliding Window Go-Back-N & Selective Repeat',
    ],
    totalQuestionsGenerated: 18,
    status: 'ready',
    summary: 'High-yield exam preparation guide focused on numerical subnetting calculations and routing protocol state diagrams.',
    documentSnippet: `In Classless Inter-Domain Routing (CIDR), an IP address is written with a prefix length (e.g. 192.168.10.0/26). The prefix /26 means 26 bits are network bits and 6 bits are host bits, giving 2^6 - 2 = 62 usable host addresses. In routing, Distance Vector uses the Bellman-Ford equation d_x(y) = min_v {c(x,v) + d_v(y)}. Link State algorithms broadcast link costs to all nodes and compute shortest paths using Dijkstra's greedy algorithm.`,
  },
];

// ==============================================================================
// 6. Validated University Exam Question Bank & Diagnostic Tests
// ==============================================================================

export const initialQuizzes: Quiz[] = [
  {
    id: 'quiz-os-eval',
    userId: 'user-student-1',
    title: 'Diagnostic Exam: Operating Systems Process Synchronization & Deadlocks',
    difficulty: 'Medium',
    competencyDomain: 'Core Computer Science',
    sourceMaterialName: 'Operating_Systems_University_Syllabus_Units_1_to_4.pdf',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-os-1',
        questionText: 'Which of the following is NOT one of the three mandatory criteria that any solution to the Critical Section problem must satisfy?',
        questionType: 'mcq',
        options: [
          'Mutual Exclusion',
          'Progress',
          'Bounded Waiting',
          'Preemptive Scheduling',
        ],
        correctAnswer: 'Preemptive Scheduling',
        explanation: 'The three classic requirements for a valid critical section solution are Mutual Exclusion (only one process in critical section at a time), Progress (selection of next process cannot be postponed indefinitely), and Bounded Waiting (a limit on the number of times other processes can enter before a request is granted).',
        topic: 'Critical Section, Mutex Locks & Semaphores',
        difficulty: 'Easy',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Silberschatz OS Concepts 10th Ed Chapter 6.1',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Standard foundational question frequently carrying 5 marks.'],
        },
        status: 'approved',
      },
      {
        id: 'q-os-2',
        questionText: 'In Banker’s Deadlock Avoidance Algorithm, if an allocation leads to a state where there exists at least one sequence <P1, P2, ..., Pn> such that each Pi’s requests can be satisfied by current available resources plus resources held by prior processes, the state is termed:',
        questionType: 'mcq',
        options: [
          'Deadlocked State',
          'Safe State',
          'Starvation State',
          'Unbounded State',
        ],
        correctAnswer: 'Safe State',
        explanation: 'A system is in a safe state if there exists a safe sequence of processes where all processes can finish execution without deadlock. An unsafe state is not necessarily deadlocked, but may lead to deadlock.',
        topic: 'Deadlock Characterization, Prevention & Banker’s Algorithm',
        difficulty: 'Medium',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Silberschatz OS Concepts Chapter 8.5',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Core concept in university operating systems exams.'],
        },
        status: 'approved',
      },
      {
        id: 'q-os-3',
        questionText: 'What is the primary phenomenon where Belady’s Anomaly occurs in Virtual Memory page replacement?',
        questionType: 'mcq',
        options: [
          'Increasing the number of allocated page frames results in more page faults under FIFO replacement',
          'LRU replacement causes unbounded thrashing under heavy multi-programming',
          'Optimal replacement algorithm cannot be implemented in hardware',
          'Page table size grows quadratically with inverted paging',
        ],
        correctAnswer: 'Increasing the number of allocated page frames results in more page faults under FIFO replacement',
        explanation: 'Belady’s Anomaly is the counter-intuitive observation that for certain page-reference strings, allocating more physical page frames causes the FIFO page replacement algorithm to incur MORE page faults instead of fewer.',
        topic: 'Virtual Memory & Page Replacement',
        difficulty: 'Medium',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Operating Systems University Exam Unit 4',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 98,
          notes: ['Frequently tested in university mid-sem and end-sem papers.'],
        },
        status: 'approved',
      },
    ],
  },
  {
    id: 'quiz-dbms-eval',
    userId: 'user-student-1',
    title: 'Diagnostic Exam: DBMS Normalization & Concurrency Control',
    difficulty: 'Hard',
    competencyDomain: 'Core Computer Science',
    sourceMaterialName: 'DBMS_University_Previous_Year_Questions_2020_2025.pdf',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-dbms-1',
        questionText: 'A relation R(A, B, C, D) has the functional dependencies F = {AB → C, C → D, D → A}. What are all the candidate keys of R?',
        questionType: 'mcq',
        options: [
          'AB, BC, BD',
          'AB only',
          'AB, BC only',
          'A, B, C, D individually',
        ],
        correctAnswer: 'AB, BC, BD',
        explanation: 'Computing closures: (AB)+ = {A,B,C,D} → AB is candidate key. Since C → D and D → A, replacing A with C gives (BC)+ = {B,C,D,A} → BC is candidate key. Replacing C with D gives (BD)+ = {B,D,A,C} → BD is candidate key. Hence, candidate keys are AB, BC, and BD.',
        topic: 'Functional Dependency Closure, Canonical Cover & BCNF Proofs',
        difficulty: 'Hard',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Korth Database Concepts Chapter 8',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Essential 10-mark calculation problem in university finals.'],
        },
        status: 'approved',
      },
      {
        id: 'q-dbms-2',
        questionText: 'Under what condition is a relational decomposition of R into R1 and R2 guaranteed to be a Lossless-Join Decomposition?',
        questionType: 'mcq',
        options: [
          'R1 ∩ R2 → R1 or R1 ∩ R2 → R2 must be in F+',
          'R1 ∪ R2 must contain all foreign keys',
          'Both R1 and R2 must already be in 3NF',
          'R1 and R2 must have an empty attribute intersection',
        ],
        correctAnswer: 'R1 ∩ R2 → R1 or R1 ∩ R2 → R2 must be in F+',
        explanation: 'According to relational database theory, a binary decomposition into R1 and R2 is lossless if and only if the common attributes (R1 ∩ R2) form a superkey for either R1 or R2 (i.e. R1 ∩ R2 → R1 or R1 ∩ R2 → R2).',
        topic: 'Functional Dependency Closure, Canonical Cover & BCNF Proofs',
        difficulty: 'Hard',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Korth Database Concepts Chapter 8.4',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Mandatory proof question in university Section B.'],
        },
        status: 'approved',
      },
    ],
  },
  {
    id: 'quiz-cn-eval',
    userId: 'user-student-1',
    title: 'Diagnostic Exam: Computer Networks Subnetting & Routing Protocols',
    difficulty: 'Hard',
    competencyDomain: 'Core Computer Science',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-cn-1',
        questionText: 'An organization is assigned the IPv4 block 192.168.1.0/24 and needs to create 4 subnets with maximum possible hosts per subnet. What is the subnet mask and the maximum number of usable host addresses per subnet?',
        questionType: 'mcq',
        options: [
          'Subnet Mask: 255.255.255.192 (/26) with 62 usable hosts per subnet',
          'Subnet Mask: 255.255.255.224 (/27) with 30 usable hosts per subnet',
          'Subnet Mask: 255.255.255.128 (/25) with 126 usable hosts per subnet',
          'Subnet Mask: 255.255.255.240 (/28) with 14 usable hosts per subnet',
        ],
        correctAnswer: 'Subnet Mask: 255.255.255.192 (/26) with 62 usable hosts per subnet',
        explanation: 'To create 4 subnets (2^2 = 4), we borrow 2 bits from the host portion: 24 + 2 = /26. The mask is 255.255.255.192. Each subnet has 32 - 26 = 6 host bits, yielding 2^6 = 64 total addresses, minus 2 (network and broadcast) = 62 usable host addresses.',
        topic: 'CIDR Subnetting, Network Masking & Host Range Calculation',
        difficulty: 'Hard',
        competencyDomain: 'Core Computer Science',
        sourceDocRef: 'Tanenbaum Computer Networks Chapter 5',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Classic numerical subnetting problem tested in university and GATE exams.'],
        },
        status: 'approved',
      },
      {
        id: 'q-cn-2',
        questionText: 'During the TCP Three-Way Handshake connection establishment, what control flags are sequentially sent by the Client, Server, and Client?',
        questionType: 'mcq',
        options: [
          'Client: SYN → Server: SYN + ACK → Client: ACK',
          'Client: ACK → Server: SYN → Client: ACK',
          'Client: SYN → Server: ACK → Client: FIN',
          'Client: PSH → Server: ACK → Client: RST',
        ],
        correctAnswer: 'Client: SYN → Server: SYN + ACK → Client: ACK',
        explanation: '1) Client sends SYN with initial sequence number ISN_c. 2) Server responds with SYN + ACK acknowledging ISN_c + 1 and sending its own ISN_s. 3) Client sends ACK acknowledging ISN_s + 1, completing the connection.',
        topic: 'Transport Layer Protocols (TCP/UDP)',
        difficulty: 'Medium',
        competencyDomain: 'Core Computer Science',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Standard protocol handshake question.'],
        },
        status: 'approved',
      },
    ],
  },
  {
    id: 'quiz-dsa-eval',
    userId: 'user-student-1',
    title: 'Diagnostic Exam: Data Structures, Algorithms & Time Complexity',
    difficulty: 'Medium',
    competencyDomain: 'Algorithms & Problem Solving',
    sourceMaterialName: 'NeetCode_150_Core_Patterns_Guide.pdf',
    createdAt: new Date().toISOString(),
    questions: [
      {
        id: 'q-dsa-1',
        questionText: 'What is the optimal time complexity to check if an array contains any duplicate elements, and which data structure achieves it?',
        questionType: 'mcq',
        options: [
          'O(N^2) using nested loops',
          'O(N) time and O(N) space using a Hash Set',
          'O(N log N) time and O(1) space with Heap Sort',
          'O(1) time using an indexed bitmask regardless of array size',
        ],
        correctAnswer: 'O(N) time and O(N) space using a Hash Set',
        explanation: 'Inserting elements into a Hash Set takes average O(1) time per item. By iterating once through the array of length N, we achieve O(N) overall time complexity with O(N) auxiliary space.',
        topic: 'Arrays, Hash Maps & Two-Pointer Search Patterns',
        difficulty: 'Easy',
        competencyDomain: 'Algorithms & Problem Solving',
        sourceDocRef: 'NeetCode 150 - Contains Duplicate / LeetCode 217',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Standard foundational DSA interview question.'],
        },
        status: 'approved',
      },
      {
        id: 'q-dsa-2',
        questionText: 'In the Two-Pointer approach for finding two numbers in a sorted array that sum to a target value, what condition determines when to decrement the right pointer (R)?',
        questionType: 'mcq',
        options: [
          'When currentSum < target',
          'When currentSum > target',
          'When left pointer equals right pointer',
          'When array[R] is negative',
        ],
        correctAnswer: 'When currentSum > target',
        explanation: 'Because the array is sorted in ascending order, if the current sum exceeds the target (currentSum > target), the only way to decrease the sum is to move the right pointer to the left (R--).',
        topic: 'Arrays, Hash Maps & Two-Pointer Search Patterns',
        difficulty: 'Medium',
        competencyDomain: 'Algorithms & Problem Solving',
        sourceDocRef: 'NeetCode 150 - Two Sum II (Sorted Array) / LeetCode 167',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Crucial pattern for O(N) two-pointer algorithmic efficiency.'],
        },
        status: 'approved',
      },
      {
        id: 'q-dsa-3',
        questionText: 'What is the worst-case time complexity of searching in a Binary Search Tree (BST) that is not self-balancing?',
        questionType: 'mcq',
        options: [
          'O(log N)',
          'O(1)',
          'O(N) when the tree degenerates into a skewed linked list',
          'O(N log N)',
        ],
        correctAnswer: 'O(N) when the tree degenerates into a skewed linked list',
        explanation: 'In an unbalanced BST (e.g. elements inserted in sorted order), each node has only one child, effectively forming a linked list of depth N, yielding worst-case O(N) search time. AVL trees prevent this by enforcing O(log N) balance factor guarantees.',
        topic: 'Binary Search Trees & AVL Balancing Invariants',
        difficulty: 'Medium',
        competencyDomain: 'Algorithms & Problem Solving',
        sourceDocRef: 'MIT 6.006 - Introduction to Algorithms (BST Invariants)',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Key distinction motivating AVL and Red-Black self-balancing trees.'],
        },
        status: 'approved',
      },
      {
        id: 'q-dsa-4',
        questionText: 'Which algorithmic paradigm solves subproblems only once and stores their results in a lookup table to avoid redundant recomputations?',
        questionType: 'mcq',
        options: [
          'Greedy Algorithm',
          'Dynamic Programming (Memoization / Tabulation)',
          'Depth First Search without caching',
          'Binary Search',
        ],
        correctAnswer: 'Dynamic Programming (Memoization / Tabulation)',
        explanation: 'Dynamic Programming solves optimization problems with Overlapping Subproblems and Optimal Substructure by caching subproblem solutions via Top-Down Memoization or Bottom-Up Tabulation.',
        topic: 'Dynamic Programming: 0/1 Knapsack, LCS & State Memoization',
        difficulty: 'Hard',
        competencyDomain: 'Algorithms & Problem Solving',
        sourceDocRef: 'Striver A-Z DSA Sheet - Dynamic Programming Masterclass',
        qualityCheck: {
          sourceSupported: true,
          singleCorrectAnswer: true,
          unambiguousOptions: true,
          noDuplicateQuestions: true,
          appropriateDifficulty: true,
          relevantToTopic: true,
          score: 100,
          notes: ['Fundamental competitive programming concept.'],
        },
        status: 'approved',
      },
    ],
  },
];

// ==============================================================================
// 7. AI Statistical Learning Assistant Personalities
// ==============================================================================

export const initialAITutors: AITutor[] = [
  {
    id: 'assistant-exam-mentor',
    userId: 'user-student-1',
    name: 'ExamMentor — Semester Exam & Concept Coach',
    avatarEmoji: '🎓',
    personality: 'Structured, Clear, Exam-Centric & Master of 10-Marker Conceptual Questions',
    systemPrompt: `You are ExamMentor, the dedicated AI Academic Coach for College Engineering Students preparing for university semester exams.
You assist students in understanding complex engineering concepts, structuring answers for 5-marker and 10-marker university questions, solving previous year question papers (PYQs), and mastering core computer science syllabus topics.
Guidelines:
1. Break down technical concepts into clean definitions, architecture diagrams/ASCII charts, and step-by-step working.
2. Highlight standard university exam traps, common numerical mistakes, and expected question formats.
3. Provide crisp summary points and formulas optimized for quick revision before exams.
4. Maintain an encouraging, focused, and academic coaching tone.`,
    isDefault: true,
    domainFocus: 'Core Computer Science',
  },
  {
    id: 'assistant-sys-tutor',
    userId: 'user-student-1',
    name: 'SysTutor — OS & Computer Networks Specialist',
    avatarEmoji: '🖥️',
    personality: 'System-Level, Rigorous & Visual for Operating Systems and Networking Protocols',
    systemPrompt: `You are SysTutor, an expert university exam mentor specializing in Operating Systems (Process Scheduling, Deadlocks, Virtual Memory Paging, File Systems) and Computer Networks (OSI/TCP-IP, Subnetting, Sliding Window, BGP/OSPF).
Provide clean numerical solutions for paging addresses, Banker's algorithm matrices, CIDR subnet calculations, and clear step-by-step protocol handshakes.`,
    isDefault: false,
    domainFocus: 'Core Computer Science',
  },
  {
    id: 'assistant-dsa-expert',
    userId: 'user-student-1',
    name: 'AlgoMentor — DSA & Coding Lab Coach',
    avatarEmoji: '⚡',
    personality: 'Intuitive, Socratic, Visual & Rigorous on Big-O Complexity and Lab Implementations',
    systemPrompt: `You are AlgoMentor, an expert Data Structures & Algorithms coach for university lab practicals and competitive coding.
You teach students how to break down complex algorithms, write clean C++/Java implementations, and optimize asymptotic time and space complexities.
Guidelines:
1. Explain algorithmic intuition using real-world mental models before jumping to code.
2. Compare approaches: Brute Force -> Optimized (Two-Pointers, Sliding Window, Monotonic Stack, Dynamic Programming, Graphs).
3. Always analyze Time and Space Complexity in Big-O notation.
4. Provide idiomatic code with line-by-line comments for lab exam submissions.
5. Highlight edge cases (empty inputs, duplicate values, cycle conditions, integer overflow).`,
    isDefault: false,
    domainFocus: 'Algorithms & Problem Solving',
  },
  {
    id: 'assistant-db-master',
    userId: 'user-student-1',
    name: 'DBMaster — Database Systems & SQL Coach',
    avatarEmoji: '🗄️',
    personality: 'Relational, Query-Oriented & Methodical on Normalization and Concurrency Control',
    systemPrompt: `You are DBMaster, a senior database systems tutor specializing in DBMS semester exams.
You help students master Relational Algebra, complex SQL joins, Functional Dependencies, Normalization (1NF through BCNF), Serializability conflict graphs, and indexing structures (B-Trees / B+ Trees).
Always provide clear proof steps for lossless join decompositions and dependency preservation.`,
    isDefault: false,
    domainFocus: 'Core Computer Science',
  },
];

// ==============================================================================
// 8. Cheatsheets & Reference Guides for College Semester Exams
// ==============================================================================

export const initialCheatsheets: CheatsheetItem[] = [
  {
    id: 'cs-os-formulas',
    title: 'Operating Systems Semester Exam Formula Sheet & Algorithms',
    subjectName: 'Core Computer Science',
    subjectColor: '#6366f1',
    category: 'OS Scheduling & Virtual Memory',
    summary: 'Essential formulas for Effective Access Time (EAT), Banker\'s Safety algorithm checks, CPU scheduling turnaround times, and page fault replacement rules.',
    keyFormulas: [
      { label: 'Turnaround Time (TAT)', formula: 'TAT = Completion Time - Arrival Time' },
      { label: 'Waiting Time (WT)', formula: 'WT = Turnaround Time - Burst Time' },
      { label: 'Effective Access Time with TLB (EAT)', formula: 'EAT = hit_rate × (tlb_access + mem_access) + (1 - hit_rate) × (tlb_access + 2 × mem_access)' },
      { label: 'Banker\'s Safety Need Matrix', formula: 'Need[i][j] = Max[i][j] - Allocation[i][j]' },
    ],
    syntaxSnippets: [
      {
        title: 'POSIX Thread Creation & Mutex Lock Pattern',
        language: 'c',
        code: `#include <pthread.h>\npthread_mutex_t lock;\n\nvoid* worker(void* arg) {\n    pthread_mutex_lock(&lock);\n    // Critical Section\n    pthread_mutex_unlock(&lock);\n    return NULL;\n}`,
        note: 'Standard C implementation required in OS lab practical exams.',
      },
    ],
    rulesOfThumb: [
      'Shortest Job First (SJF) is provably optimal for minimizing average waiting time but requires prior burst prediction.',
      'Thrashing occurs when total memory allocated to active processes is less than their combined working set size (∑ WSS_i > Total RAM).',
    ],
    lastUpdated: '2026-09-10',
  },
  {
    id: 'cs-dbms-formulas',
    title: 'DBMS Normalization & Relational Algebra Quick-Sheet',
    subjectName: 'Core Computer Science',
    subjectColor: '#0ea5e9',
    category: 'Relational Database Design',
    summary: 'Step-by-step algorithms for computing Attribute Closure, minimal cover, testing lossless join decomposition, and checking 3NF vs BCNF compliance.',
    keyFormulas: [
      { label: 'Boyce-Codd Normal Form (BCNF) Rule', formula: 'For every non-trivial FD X -> Y, X must be a Super Key.' },
      { label: 'Third Normal Form (3NF) Rule', formula: 'For every non-trivial FD X -> Y, either X is a Super Key OR Y is a Prime Attribute.' },
      { label: 'B+ Tree Order (p) Max Keys in Leaf', formula: 'Max Keys = p - 1; Min Keys = ⌈(p - 1)/2⌉' },
      { label: 'Lossless Join Condition for R1 and R2', formula: '(R1 ∩ R2 -> R1) OR (R1 ∩ R2 -> R2) must hold in F+' },
    ],
    syntaxSnippets: [
      {
        title: 'ACID Compliant Transaction Block in SQL',
        language: 'sql',
        code: `BEGIN TRANSACTION;\nUPDATE Accounts SET balance = balance - 500 WHERE acc_no = 101;\nUPDATE Accounts SET balance = balance + 500 WHERE acc_no = 202;\n-- Check constraints before commit\nCOMMIT;\n-- In case of failure: ROLLBACK;`,
        note: 'Frequent question in University DBMS Part-B 10-markers.',
      },
    ],
    rulesOfThumb: [
      'BCNF does not always preserve functional dependencies, whereas 3NF always guarantees both lossless join and dependency preservation.',
      'In conflict serializability, construct a precedence graph: an edge Ti -> Tj exists if Ti and Tj perform conflicting operations on the same data item and Ti executes first. If acyclic, it is conflict serializable.',
    ],
    lastUpdated: '2026-09-15',
  },
  {
    id: 'cs-cn-formulas',
    title: 'Computer Networks Subnetting & Flow Control Exam Sheet',
    subjectName: 'Core Computer Science',
    subjectColor: '#10b981',
    category: 'Computer Networks & TCP/IP',
    summary: 'Subnet masking, CIDR host calculations, Sliding Window protocol efficiency, and Hamming code error detection math for semester exams.',
    keyFormulas: [
      { label: 'Usable Hosts in IPv4 CIDR /n', formula: 'Usable Hosts = 2^(32 - n) - 2' },
      { label: 'Stop-and-Wait Protocol Efficiency (η)', formula: 'η = 1 / (1 + 2a), where a = Propagation Delay (Tp) / Transmission Time (Tt)' },
      { label: 'Go-Back-N Window Size Capacity', formula: 'Max Sender Window W_s = 2^k - 1 (for k-bit sequence numbers)' },
      { label: 'Hamming Code Redundancy Bits condition', formula: '2^r >= m + r + 1 (m message bits, r parity bits)' },
    ],
    syntaxSnippets: [
      {
        title: 'Socket Programming (TCP Server in Python)',
        language: 'python',
        code: `import socket\ns = socket.socket(socket.AF_INET, socket.SOCK_STREAM)\ns.bind(('127.0.0.1', 8080))\ns.listen(5)\nconn, addr = s.accept()\ndata = conn.recv(1024)\nconn.sendall(b"HTTP/1.1 200 OK\\r\\n\\r\\nHello Student!")\nconn.close()`,
        note: 'Standard viva / lab question for Computer Networks practicals.',
      },
    ],
    rulesOfThumb: [
      'Two addresses in any IPv4 subnet are always reserved: network ID (all host bits 0) and directed broadcast address (all host bits 1).',
      'Selective Repeat protocol requires W_s + W_r <= 2^k, so maximum sender and receiver window is 2^(k-1).',
    ],
    lastUpdated: '2026-09-18',
  },
];

export const initialLearningResources: LearningResource[] = [
  {
    id: 'res-exam-os-sheet',
    topicId: 'top-os-paging',
    topicTitle: 'Virtual Memory Paging & Page Replacement',
    subjectName: 'Operating Systems',
    title: 'Interactive Cheatsheet: OS Scheduling & Virtual Memory Formulas',
    resourceType: 'cheatsheet',
    url: '#cheatsheet-os-formulas',
    difficultyLevel: 'Medium',
    estimatedMins: 15,
    recommendedReason: 'Quick formula recap of Effective Access Time (EAT), Belady\'s Anomaly, and Banker\'s Safety algorithm.',
    qualityScore: 5.0,
    sourcePlatform: 'University Exam Vault',
    cheatsheetData: initialCheatsheets[0],
  },
  {
    id: 'res-exam-nptel-os',
    topicId: 'top-os-deadlocks',
    topicTitle: 'Deadlock Detection & Avoidance',
    subjectName: 'Operating Systems',
    title: 'NPTEL SWAYAM: Operating Systems by Prof. Santanu Chattopadhyay',
    resourceType: 'course',
    url: 'https://nptel.ac.in/courses/106105214',
    difficultyLevel: 'Medium',
    estimatedMins: 60,
    recommendedReason: 'Top university recommended video lectures for comprehensive theoretical foundations.',
    qualityScore: 4.9,
    sourcePlatform: 'NPTEL / SWAYAM',
  },
  {
    id: 'res-exam-dbms-sheet',
    topicId: 'top-dbms-normalization',
    topicTitle: 'Functional Dependencies & Normal Forms (1NF to BCNF)',
    subjectName: 'Database Management Systems',
    title: 'Interactive Cheatsheet: DBMS Normalization & SQL Exam Sheet',
    resourceType: 'cheatsheet',
    url: '#cheatsheet-dbms-formulas',
    difficultyLevel: 'Medium',
    estimatedMins: 20,
    recommendedReason: 'Clear step-by-step proofs for testing lossless join decomposition and BCNF compliance.',
    qualityScore: 4.95,
    sourcePlatform: 'University Exam Vault',
    cheatsheetData: initialCheatsheets[1],
  },
  {
    id: 'res-dsa-blind75',
    topicId: 'top-dsa-trees',
    topicTitle: 'Binary Search Trees & Heap Invariants',
    subjectName: 'Data Structures & Algorithms',
    title: 'NeetCode 150 & Blind 75 DSA Visual Roadmap',
    resourceType: 'practice',
    url: 'https://neetcode.io/roadmap',
    difficultyLevel: 'Medium',
    estimatedMins: 45,
    recommendedReason: 'Visual interactive dependency graph of essential algorithmic patterns, space/time complexities, and video breakdowns.',
    qualityScore: 4.98,
    sourcePlatform: 'NeetCode',
  },
  {
    id: 'res-dsa-leetcode',
    topicId: 'top-dsa-dp',
    topicTitle: 'Dynamic Programming: 0/1 Knapsack & LCS',
    subjectName: 'Data Structures & Algorithms',
    title: 'LeetCode Tree & Graph Exploration Sandbox',
    resourceType: 'practice',
    url: 'https://leetcode.com/explore/learn/card/data-structures-and-algorithms/',
    difficultyLevel: 'Hard',
    estimatedMins: 60,
    recommendedReason: 'Hands-on browser-based compilation sandbox with 10,000+ unit test testcases to verify edge cases.',
    qualityScore: 4.95,
    sourcePlatform: 'LeetCode',
  },
  {
    id: 'res-dsa-mit',
    topicId: 'top-dsa-dp',
    topicTitle: 'Dynamic Programming & State Transitions',
    subjectName: 'Data Structures & Algorithms',
    title: 'MIT 6.006: Introduction to Algorithms & Dynamic Programming',
    resourceType: 'video',
    url: 'https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/',
    difficultyLevel: 'Hard',
    estimatedMins: 55,
    recommendedReason: 'World-renowned lecture series by Prof. Erik Demaine on recurrence equations, memoization trees, and DAG shortest paths.',
    qualityScore: 4.99,
    sourcePlatform: 'MIT OpenCourseWare',
  },
  {
    id: 'res-exam-cn-sheet',
    topicId: 'top-cn-subnetting',
    topicTitle: 'IPv4 CIDR Subnetting & Supernetting',
    subjectName: 'Computer Networks',
    title: 'Interactive Cheatsheet: Computer Networks Subnetting & Protocols',
    resourceType: 'cheatsheet',
    url: '#cheatsheet-cn-formulas',
    difficultyLevel: 'Medium',
    estimatedMins: 20,
    recommendedReason: 'Essential formulas for CIDR host ranges, Hamming parity calculation, and Sliding Window efficiency.',
    qualityScore: 4.92,
    sourcePlatform: 'University Exam Vault',
    cheatsheetData: initialCheatsheets[2],
  },
];

// ==============================================================================
// 9. Department Academic Metrics & Heatmap for College Deans & HODs
// ==============================================================================

export const initialDepartmentMetrics: DepartmentWorkforceMetric[] = [
  {
    departmentId: 'dept-cse',
    departmentName: 'Computer Science & Engineering (CSE)',
    ministry: 'School of Computing',
    totalOfficials: 240,
    averageCompetency: 78,
    trainingCompletionRate: 85,
    criticalGapCount: 16,
    domainScores: {
      statistical: 82,
      technical: 78,
      digitalGovernance: 74,
      behavioural: 80,
    },
    priorityGaps: ['Virtual Memory Paging (52%)', 'Dynamic Programming Patterns (44%)'],
  },
  {
    departmentId: 'dept-it',
    departmentName: 'Information Technology (IT)',
    ministry: 'School of Computing',
    totalOfficials: 180,
    averageCompetency: 74,
    trainingCompletionRate: 78,
    criticalGapCount: 22,
    domainScores: {
      statistical: 76,
      technical: 72,
      digitalGovernance: 70,
      behavioural: 76,
    },
    priorityGaps: ['TCP Congestion Control (48%)', 'SQL Query Optimization (54%)'],
  },
  {
    departmentId: 'dept-aids',
    departmentName: 'Artificial Intelligence & Data Science (AI & DS)',
    ministry: 'School of Computing',
    totalOfficials: 120,
    averageCompetency: 83,
    trainingCompletionRate: 91,
    criticalGapCount: 9,
    domainScores: {
      statistical: 88,
      technical: 84,
      digitalGovernance: 79,
      behavioural: 82,
    },
    priorityGaps: ['GPU Memory Architectures (56%)', 'Probabilistic Data Structures (60%)'],
  },
  {
    departmentId: 'dept-ece',
    departmentName: 'Electronics & Communication Engineering (ECE)',
    ministry: 'School of Electrical Sciences',
    totalOfficials: 210,
    averageCompetency: 68,
    trainingCompletionRate: 67,
    criticalGapCount: 34,
    domainScores: {
      statistical: 70,
      technical: 65,
      digitalGovernance: 62,
      behavioural: 72,
    },
    priorityGaps: ['Microprocessor Bus Arbitration (40%)', 'Embedded OS Real-Time Scheduling (50%)'],
  },
];

// ==============================================================================
// 10. AI Predictive Analytics: High-Yield Skills for University Exams & Placements
// ==============================================================================

export const initialEmergingSkills: EmergingSkillPrediction[] = [
  {
    id: 'es-1',
    skillName: 'Operating System Kernel & Memory Subsystems',
    growthCategory: 'Critical Demand',
    urgencyLevel: 'Immediate (0-6 mo)',
    projectedAdoptionRate: 92,
    primaryDrivers: [
      'Core university end-semester mandatory 10-marker theory weightage',
      'System-level questions in tech giant placement rounds (OS concurrency & page faults)',
      'Linux kernel internals required for systems engineering labs',
    ],
    recommendedPrograms: [
      'NPTEL SWAYAM: Operating Systems by IIT Kharagpur',
      'MIT 6.828: Operating System Engineering Lab Sprint',
    ],
    applicableCadres: ['B.Tech CSE 3rd Year', 'B.Tech IT 3rd Year', 'M.Tech Computer Science'],
  },
  {
    id: 'es-2',
    skillName: 'Relational Database Internals & BCNF Decomposition',
    growthCategory: 'Critical Demand',
    urgencyLevel: 'Immediate (0-6 mo)',
    projectedAdoptionRate: 88,
    primaryDrivers: [
      'High-frequency exam questions on functional dependencies and minimal cover',
      'Database transaction ACID properties and conflict serializability graphs',
    ],
    recommendedPrograms: ['NPTEL: Database Management System by IIT Madras'],
    applicableCadres: ['B.Tech CSE 3rd Year', 'B.Tech IT 3rd Year'],
  },
  {
    id: 'es-3',
    skillName: 'Computer Networks Protocol Design & Subnet Math',
    growthCategory: 'High Impact',
    urgencyLevel: 'Immediate (0-6 mo)',
    projectedAdoptionRate: 82,
    primaryDrivers: [
      'Compulsory numericals on CIDR subnets and Stop-and-Wait protocol efficiency',
      'University semester exam network socket programming viva',
    ],
    recommendedPrograms: ['NPTEL: Computer Networks and Internet Protocol by IIT Kharagpur'],
    applicableCadres: ['B.Tech CSE 3rd Year', 'B.Tech ECE 3rd Year'],
  },
  {
    id: 'es-4',
    skillName: 'Dynamic Programming & Graph Algorithmic Patterns',
    growthCategory: 'High Impact',
    urgencyLevel: 'Strategic (6-18 mo)',
    projectedAdoptionRate: 94,
    primaryDrivers: [
      'University Algorithm Design (DAA) end-semester paper and placement OA tests',
      'Crucial for high GPA ranking and competitive programming contests',
    ],
    recommendedPrograms: ['MIT 6.006: Introduction to Algorithms', 'NeetCode 150 Core Patterns'],
    applicableCadres: ['All Engineering Disciplines'],
  },
];

// ==============================================================================
// 11. System Notifications, Events & Badges
// ==============================================================================

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'user-student-1',
    title: '🔴 Critical Exam Topic Gap Detected',
    message: 'AI Diagnostic detected Virtual Memory Paging (42%) and Deadlock Avoidance (50%) as priority gaps for your upcoming OS Mid-Semester exam.',
    notificationType: 'competency_gap',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'notif-2',
    userId: 'user-student-1',
    title: 'Recommended Exam Preparation Module',
    message: 'Start "Operating Systems: Theory & Algorithms University Sprint" to cover high-probability 10-marker questions (+18% projected score boost).',
    notificationType: 'course_recommended',
    isRead: false,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: 'user-student-1',
    title: 'DBMS Lab Practical Evaluation Verified',
    message: 'Your recent evaluation in "SQL Joins, Indexing & BCNF Normalization" was graded 9.4/10 (Top 5% in CSE Section A).',
    notificationType: 'achievement',
    isRead: true,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const initialAcademicEvents: AcademicEvent[] = [
  {
    id: 'event-1',
    userId: 'user-student-1',
    subjectId: 'subj-os-systems',
    subjectName: 'Operating Systems (CS301)',
    subjectColor: '#6366f1',
    title: 'Operating Systems Mid-Semester Exam',
    eventType: 'practical',
    eventDate: new Date(Date.now() + 12 * 86400000).toISOString(),
    weightagePercentage: 40,
    syllabusCoverageNeeded: 85,
  },
  {
    id: 'event-2',
    userId: 'user-student-1',
    subjectId: 'subj-dbms-sql',
    subjectName: 'Database Management Systems (CS302)',
    subjectColor: '#0ea5e9',
    title: 'DBMS End-Semester Lab Practical & Viva',
    eventType: 'project',
    eventDate: new Date(Date.now() + 18 * 86400000).toISOString(),
    weightagePercentage: 35,
    syllabusCoverageNeeded: 100,
  },
];

export const initialAchievements: Achievement[] = [
  {
    id: 'ach-1',
    badgeId: 'dean-honors',
    title: 'Dean\'s Honors Scholar',
    description: 'Maintained outstanding performance across all semester subject diagnostic quizzes (>85% score).',
    icon: '🎓',
    unlockedAt: '2026-08-15T12:00:00.000Z',
  },
  {
    id: 'ach-2',
    badgeId: 'exam-sprint-master',
    title: 'Exam Sprint Master',
    description: 'Completed 40+ hours of focused timetable study sessions aligned with university syllabus.',
    icon: '📚',
    unlockedAt: '2026-08-20T17:00:00.000Z',
  },
  {
    id: 'ach-3',
    badgeId: 'streak-14',
    title: 'Consistent Study Streak',
    description: 'Maintained 14 consecutive days of active timetable study and revision.',
    icon: '🔥',
    unlockedAt: '2026-08-28T08:00:00.000Z',
  },
];

// Spaced revision items for exam retention
export const initialSpacedRevisions: SpacedRevision[] = [
  {
    id: 'rev-1',
    userId: 'user-student-1',
    topicId: 'top-os-paging',
    topicTitle: 'Virtual Memory Paging & Effective Access Time (EAT)',
    subjectName: 'Core Computer Science',
    subjectColor: '#6366f1',
    repetitionNumber: 3,
    easeFactor: 2.6,
    intervalDays: 7,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 4,
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'rev-2',
    userId: 'user-student-1',
    topicId: 'top-dbms-normalization',
    topicTitle: 'BCNF vs 3NF Decomposition & Lossless Join Tests',
    subjectName: 'Core Computer Science',
    subjectColor: '#0ea5e9',
    repetitionNumber: 1,
    easeFactor: 2.1,
    intervalDays: 2,
    nextReviewDate: todayStr,
    status: 'due',
    lastRating: 2,
    updatedAt: new Date().toISOString(),
  },
];

// University exam quiz challenge & peer battles
export const initialBattleQuestions: BattleQuestion[] = [
  {
    id: 'bq-1',
    subject: 'Operating Systems',
    questionText: 'Which page replacement algorithm can suffer from Belady\'s Anomaly (where increasing page frames increases page faults)?',
    options: ['First-In First-Out (FIFO)', 'Optimal Page Replacement (OPT)', 'Least Recently Used (LRU)', 'Working Set Model'],
    correctAnswer: 'First-In First-Out (FIFO)',
    explanation: 'FIFO is not a stack algorithm, meaning the set of pages in memory for n frames is not always a subset of pages in n+1 frames, allowing Belady\'s Anomaly.',
    difficulty: 'Hard',
    points: 100,
    timeLimitSec: 20,
  },
];

export const initialChallengers: BattleChallenger[] = [
  {
    id: 'chal-1',
    name: 'Rohan Verma',
    handle: 'Rohan_CSE21',
    avatarEmoji: '⚡',
    title: 'B.Tech CSE, 6th Semester (Section B)',
    university: 'Apex Institute of Technology',
    eloRating: 1850,
    tier: 'Platinum',
    winRate: 78,
    totalBattles: 28,
    wins: 22,
    losses: 6,
    streak: 4,
    favoriteSubject: 'Operating Systems & Networks',
    isOnline: true,
  },
];

export const initialLeaderboard: LeaderboardEntry[] = [
  {
    id: 'lead-1',
    rank: 1,
    fullName: 'Aarav Sharma',
    handle: 'Aarav_21BCS',
    avatarEmoji: '🎓',
    university: 'Apex Institute of Technology — B.Tech CSE',
    eloRating: 2150,
    tier: 'Diamond',
    winRate: 86,
    wins: 38,
    losses: 6,
    streak: 7,
    totalXp: 3420,
    subjectBadges: ['OS Systems Ace', 'DBMS Specialist'],
    isCurrentUser: true,
  },
];

export const initialStudentBattleProfile: StudentBattleProfile = {
  id: 'user-student-1',
  fullName: 'Aarav Sharma',
  handle: 'Aarav_21BCS',
  avatarEmoji: '🎓',
  title: 'B.Tech CSE, 6th Semester (Roll: 21BCS0842)',
  university: 'Apex Institute of Technology',
  eloRating: 2150,
  tier: 'Diamond',
  totalBattles: 44,
  wins: 38,
  losses: 6,
  winRate: 86,
  currentStreak: 7,
  bestStreak: 11,
  totalXp: 3420,
  radarStats: [
    { subject: 'Operating Systems', score: 84 },
    { subject: 'Database Systems', score: 82 },
    { subject: 'Computer Networks', score: 75 },
    { subject: 'DSA & Algorithms', score: 78 },
    { subject: 'Software Engineering', score: 70 },
  ],
  showcaseBadges: [
    {
      id: 'b-dean',
      title: 'Dean\'s List Scholar',
      icon: '🎓',
      rarity: 'Legendary',
      description: 'Maintained top 5% competency score in semester university diagnostics.',
    },
  ],
  recentMatches: [
    {
      id: 'm-1',
      opponentName: 'Rohan Verma',
      opponentAvatar: '⚡',
      opponentTier: 'Platinum',
      userScore: 480,
      opponentScore: 410,
      result: 'Victory',
      eloChange: +24,
      subject: 'Operating Systems (Virtual Memory)',
      date: 'Today, 08:30 AM',
    },
  ],
};
